// Autogenerated file: DO NOT EDIT
// Created on 2025-04-07 4:05:19 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct ButterflyCurve: IAngularCurve2D, IOpenShape
    {
        // Fields

        // With functions 

        // Regular Constructor

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static ButterflyCurve Create() => new ButterflyCurve();

        // Static default implementation
        public static readonly ButterflyCurve Default = default;

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is ButterflyCurve;
        [MethodImpl(AggressiveInlining)] public Boolean Equals(ButterflyCurve other) => true;
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(ButterflyCurve other) => false;
        [MethodImpl(AggressiveInlining)] public static Boolean operator==(ButterflyCurve a, ButterflyCurve b) => true;
        [MethodImpl(AggressiveInlining)] public static Boolean operator!=(ButterflyCurve a, ButterflyCurve b) => false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes();
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{  }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)]  public Vector2 Eval(Angle t) => t.ButterflyCurve;
[MethodImpl(AggressiveInlining)]  public Vector2 Eval(Number t) => this.Eval(t.Turns);
[MethodImpl(AggressiveInlining)]  public IArray<Vector2> Sample(Integer numPoints){
            var _var68 = this;
            return numPoints.LinearSpace.Map((x)  => _var68.Eval(x));
        }

[MethodImpl(AggressiveInlining)]  public PolyLine2D ToPolyLine2D(Integer numPoints) => (this.Sample(numPoints), this.Closed);
public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => ((Boolean)false); } 

        // Unimplemented interface functions
    }
}
