// Autogenerated file: DO NOT EDIT
// Created on 2025-03-14 12:36:59 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct CycloidOfCeva: IPolarCurve, IOpenShape
    {
        // Fields

        // With functions 

        // Regular Constructor

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static CycloidOfCeva Create() => new CycloidOfCeva();

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is CycloidOfCeva;
        [MethodImpl(AggressiveInlining)] public Boolean Equals(CycloidOfCeva other) => true;
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(CycloidOfCeva other) => false;
        [MethodImpl(AggressiveInlining)] public static Boolean operator==(CycloidOfCeva a, CycloidOfCeva b) => true;
        [MethodImpl(AggressiveInlining)] public static Boolean operator!=(CycloidOfCeva a, CycloidOfCeva b) => false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes();
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{  }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        // GetRadius(CycloidOfCeva, Angle):Number; [Self=CycloidOfCeva;]; <>
        [MethodImpl(AggressiveInlining)]  public Number GetRadius(Angle t) => t.CycloidOfCeva;
// EvalPolar(CycloidOfCeva, Angle):PolarCoordinate; [IPolarCurve=CycloidOfCeva;Self=CycloidOfCeva;]; <>
        [MethodImpl(AggressiveInlining)]  public PolarCoordinate EvalPolar(Angle t) => (this.GetRadius(t), t);
// Eval(CycloidOfCeva, Angle):Vector2; [IPolarCurve=CycloidOfCeva;Self=CycloidOfCeva;]; <>
        [MethodImpl(AggressiveInlining)]  public Vector2 Eval(Angle t) => this.EvalPolar(t);
// Eval(CycloidOfCeva, Number):Vector2; [IAngularCurve2D=CycloidOfCeva;IPolarCurve=CycloidOfCeva;Self=CycloidOfCeva;]; <>
        [MethodImpl(AggressiveInlining)]  public Vector2 Eval(Number t) => this.Eval(t.Turns);
// Sample(CycloidOfCeva, Integer):_T0; [ICurve2D=CycloidOfCeva;IAngularCurve2D=CycloidOfCeva;IPolarCurve=CycloidOfCeva;Self=CycloidOfCeva;]; <_T0:IArray<Vector2>>
        [MethodImpl(AggressiveInlining)]  public _T0 Sample<_T0>(Integer numPoints){
            var _var66 = this;
            return numPoints.LinearSpace.Map((x)  => _var66.Eval(x));
        }

// ToPolyLine2D(CycloidOfCeva, Integer):PolyLine2D; [ICurve2D=CycloidOfCeva;IAngularCurve2D=CycloidOfCeva;IPolarCurve=CycloidOfCeva;Self=CycloidOfCeva;]; <>
        [MethodImpl(AggressiveInlining)]  public PolyLine2D ToPolyLine2D(Integer numPoints) => (this.Sample(numPoints), this.Closed);
// Closed(CycloidOfCeva):Boolean; [IOpenShape=CycloidOfCeva;Self=CycloidOfCeva;]; <>
        public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => ((Boolean)false); } 

        // Unimplemented concept functions
    }
}
