// Autogenerated file: DO NOT EDIT
// Created on 2025-03-09 8:08:08 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
public partial struct CycloidOfCeva: IPolarCurve, IOpenShape
{
    // Fields

    // With functions 

    // Regular Constructor

    // Static factory function
    [MethodImpl(AggressiveInlining)] public static CycloidOfCeva Create() => new CycloidOfCeva();

    // Object virtual function overrides: Equals, GetHashCode, ToString
    [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is CycloidOfCeva;
    [MethodImpl(AggressiveInlining)] public Boolean Equals(CycloidOfCeva other) => true;
    [MethodImpl(AggressiveInlining)] public Boolean NotEquals(CycloidOfCeva other) => false;
    [MethodImpl(AggressiveInlining)] public static Boolean operator==(CycloidOfCeva a, CycloidOfCeva b) => true;
    [MethodImpl(AggressiveInlining)] public static Boolean operator!=(CycloidOfCeva a, CycloidOfCeva b) => false;
    [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes();
    [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{  }}";

    // Explicit implementation of interfaces by forwarding properties to fields

    // Implemented concept functions and type functions
    [MethodImpl(AggressiveInlining)]  public Number GetRadius(Angle t) => t.CycloidOfCeva;
[MethodImpl(AggressiveInlining)]  public PolarCoordinate EvalPolar(Angle t) => (this.GetRadius(t), t);
[MethodImpl(AggressiveInlining)]  public Vector2 Eval(Angle t) => this.EvalPolar(t);
[MethodImpl(AggressiveInlining)]  public Vector2 Eval(Number t) => this.Eval(t.Turns);
[MethodImpl(AggressiveInlining)]  public IArray<Vector2> Sample(Integer numPoints){
    var _var257 = this;
    return numPoints.LinearSpace.Map((x) =>  => _var257.Eval(x);
;
}

[MethodImpl(AggressiveInlining)]  public PolyLine2D ToPolyLine2D(Integer numPoints) => (this.Sample(numPoints), this.Closed);
[MethodImpl(AggressiveInlining)]  public Procedural<Number, TR> Combine<TR>(CycloidOfCeva b, System.Func<TR, TR, TR> f){
    var _var260 = b;
    {
        var _var259 = this;
        {
            var _var258 = f;
            return (x) =>  => _var258.Invoke(_var259.Eval(x), _var260.Eval(x));
;
        }
    }
}

[MethodImpl(AggressiveInlining)]  public Procedural<TR, Vector2> MapDomain<T0, TR>(System.Func<T0, TR> f){
    var _var262 = f;
    {
        var _var261 = this;
        return new Procedural<$TIn2,$TOut>((x) =>  => _var261.Eval(_var262.Invoke(x));
;
    }
}

public System.Func<Number, Vector2> Function { [MethodImpl(AggressiveInlining)] get {
    var _var263 = this;
    return (x) =>  => _var263.Eval(x);
;
}
 } 
[MethodImpl(AggressiveInlining)]  public Procedural<Number, Vector2> Compose(CycloidOfCeva b){
    var _var265 = this;
    {
        var _var264 = b;
        return new Procedural<$TIn2,$TOut>((x) =>  => _var264.Eval(_var265.Eval(x));
;
    }
}

[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, TR> Combine<TR>(CycloidOfCeva b, System.Func<TR, TR, TR> f){
    var _var268 = b;
    {
        var _var267 = this;
        {
            var _var266 = f;
            return (x) =>  => _var266.Invoke(_var267.Eval(x), _var268.Eval(x));
;
        }
    }
}

[MethodImpl(AggressiveInlining)]  public Procedural<TR, Number> MapDomain<T0, TR>(System.Func<T0, TR> f){
    var _var270 = f;
    {
        var _var269 = this;
        return new Procedural<$TIn2,$TOut>((x) =>  => _var269.Eval(_var270.Invoke(x));
;
    }
}

public System.Func<Vector2, Number> Function { [MethodImpl(AggressiveInlining)] get {
    var _var271 = this;
    return (x) =>  => _var271.Eval(x);
;
}
 } 
[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, Number> Compose(CycloidOfCeva b){
    var _var273 = this;
    {
        var _var272 = b;
        return new Procedural<$TIn2,$TOut>((x) =>  => _var272.Eval(_var273.Eval(x));
;
    }
}

[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, $TOut> Union(CycloidOfCeva b) => this.Combine(b, (a, b) =>  => a.Max(b);

[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, $TOut> Intersection(CycloidOfCeva b) => this.Combine(b, (a, b) =>  => a.Min(b);

[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, $TOut> Difference(CycloidOfCeva b) => this.Combine(b, (a, b) =>  => a.Max(b.Negative);

public Procedural<Vector2, Number> Inverse { [MethodImpl(AggressiveInlining)] get  => this.Map((x) =>  => x.Negative;
 } 
[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, Boolean> Threshold(Number threshold){
    var _var274 = threshold;
    return this.Map((x) =>  => x.GreaterThanOrEquals(_var274);
;
}

public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => ((Boolean)false); } 

    // Unimplemented concept functions
    [MethodImpl(AggressiveInlining)]  public Number Distance(Vector2 p) => throw new NotImplementedException();
[MethodImpl(AggressiveInlining)]  public Number Eval(Vector2 t) => throw new NotImplementedException();
}
Plato.CSharpWriter.CSharpConcreteTypeWriter}
