// Autogenerated file: DO NOT EDIT
// Created on 2025-03-09 8:08:08 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
public partial struct FermatsSpiral: IPolarCurve, IOpenShape
{
    // Fields
    [DataMember] public readonly Number A;

    // With functions 
    [MethodImpl(AggressiveInlining)] public FermatsSpiral WithA(Number a) => new FermatsSpiral(a);

    // Regular Constructor
    [MethodImpl(AggressiveInlining)] public FermatsSpiral(Number a) { A = a; }

    // Static factory function
    [MethodImpl(AggressiveInlining)] public static FermatsSpiral Create(Number a) => new FermatsSpiral(a);

    // Implicit converters to/from single field
    [MethodImpl(AggressiveInlining)] public static implicit operator Number(FermatsSpiral self) => self.A;
    [MethodImpl(AggressiveInlining)] public static implicit operator FermatsSpiral(Number value) => new FermatsSpiral(value);
    [MethodImpl(AggressiveInlining)] public static implicit operator FermatsSpiral(Integer value) => new FermatsSpiral(value);
    [MethodImpl(AggressiveInlining)] public static implicit operator FermatsSpiral(int value) => new Integer(value);
    [MethodImpl(AggressiveInlining)] public static implicit operator FermatsSpiral(float value) => new Number(value);
    [MethodImpl(AggressiveInlining)] public static implicit operator float(FermatsSpiral value) => value.A;

    // Object virtual function overrides: Equals, GetHashCode, ToString
    [MethodImpl(AggressiveInlining)] public Boolean Equals(FermatsSpiral other) => A.Equals(other.A);
    [MethodImpl(AggressiveInlining)] public Boolean NotEquals(FermatsSpiral other) => !A.Equals(other.A);
    [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is FermatsSpiral other ? Equals(other) : false;
    [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(A);
    [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"A\" = {A} }}";

    // Explicit implementation of interfaces by forwarding properties to fields

    // Implemented concept functions and type functions
    [MethodImpl(AggressiveInlining)]  public Number GetRadius(Angle t) => t.FermatsSpiral(this.A);
[MethodImpl(AggressiveInlining)]  public PolarCoordinate EvalPolar(Angle t) => (this.GetRadius(t), t);
[MethodImpl(AggressiveInlining)]  public Vector2 Eval(Angle t) => this.EvalPolar(t);
[MethodImpl(AggressiveInlining)]  public Vector2 Eval(Number t) => this.Eval(t.Turns);
[MethodImpl(AggressiveInlining)]  public IArray<Vector2> Sample(Integer numPoints){
    var _var455 = this;
    return numPoints.LinearSpace.Map((x) =>  => _var455.Eval(x);
;
}

[MethodImpl(AggressiveInlining)]  public PolyLine2D ToPolyLine2D(Integer numPoints) => (this.Sample(numPoints), this.Closed);
[MethodImpl(AggressiveInlining)]  public Procedural<Number, TR> Combine<TR>(FermatsSpiral b, System.Func<TR, TR, TR> f){
    var _var458 = b;
    {
        var _var457 = this;
        {
            var _var456 = f;
            return (x) =>  => _var456.Invoke(_var457.Eval(x), _var458.Eval(x));
;
        }
    }
}

[MethodImpl(AggressiveInlining)]  public Procedural<TR, Vector2> MapDomain<T0, TR>(System.Func<T0, TR> f){
    var _var460 = f;
    {
        var _var459 = this;
        return new Procedural<$TIn2,$TOut>((x) =>  => _var459.Eval(_var460.Invoke(x));
;
    }
}

public System.Func<Number, Vector2> Function { [MethodImpl(AggressiveInlining)] get {
    var _var461 = this;
    return (x) =>  => _var461.Eval(x);
;
}
 } 
[MethodImpl(AggressiveInlining)]  public Procedural<Number, Vector2> Compose(FermatsSpiral b){
    var _var463 = this;
    {
        var _var462 = b;
        return new Procedural<$TIn2,$TOut>((x) =>  => _var462.Eval(_var463.Eval(x));
;
    }
}

[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, TR> Combine<TR>(FermatsSpiral b, System.Func<TR, TR, TR> f){
    var _var466 = b;
    {
        var _var465 = this;
        {
            var _var464 = f;
            return (x) =>  => _var464.Invoke(_var465.Eval(x), _var466.Eval(x));
;
        }
    }
}

[MethodImpl(AggressiveInlining)]  public Procedural<TR, Number> MapDomain<T0, TR>(System.Func<T0, TR> f){
    var _var468 = f;
    {
        var _var467 = this;
        return new Procedural<$TIn2,$TOut>((x) =>  => _var467.Eval(_var468.Invoke(x));
;
    }
}

public System.Func<Vector2, Number> Function { [MethodImpl(AggressiveInlining)] get {
    var _var469 = this;
    return (x) =>  => _var469.Eval(x);
;
}
 } 
[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, Number> Compose(FermatsSpiral b){
    var _var471 = this;
    {
        var _var470 = b;
        return new Procedural<$TIn2,$TOut>((x) =>  => _var470.Eval(_var471.Eval(x));
;
    }
}

[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, $TOut> Union(FermatsSpiral b) => this.Combine(b, (a, b) =>  => a.Max(b);

[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, $TOut> Intersection(FermatsSpiral b) => this.Combine(b, (a, b) =>  => a.Min(b);

[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, $TOut> Difference(FermatsSpiral b) => this.Combine(b, (a, b) =>  => a.Max(b.Negative);

public Procedural<Vector2, Number> Inverse { [MethodImpl(AggressiveInlining)] get  => this.Map((x) =>  => x.Negative;
 } 
[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, Boolean> Threshold(Number threshold){
    var _var472 = threshold;
    return this.Map((x) =>  => x.GreaterThanOrEquals(_var472);
;
}

public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => ((Boolean)false); } 

    // Unimplemented concept functions
    [MethodImpl(AggressiveInlining)]  public Number Distance(Vector2 p) => throw new NotImplementedException();
[MethodImpl(AggressiveInlining)]  public Number Eval(Vector2 t) => throw new NotImplementedException();
}
Plato.CSharpWriter.CSharpConcreteTypeWriter}
