// Autogenerated file: DO NOT EDIT
// Created on 2025-04-08 12:25:04 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct MatrixTransform2D: ITransform2D
    {
        // Fields
        [DataMember] public readonly Matrix3x2 Matrix;

        // With functions 
        [MethodImpl(AggressiveInlining)] public MatrixTransform2D WithMatrix(Matrix3x2 matrix) => new MatrixTransform2D(matrix);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public MatrixTransform2D(Matrix3x2 matrix) { Matrix = matrix; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static MatrixTransform2D Create(Matrix3x2 matrix) => new MatrixTransform2D(matrix);

        // Static default implementation
        public static readonly MatrixTransform2D Default = default;

        // Implicit converters to/from single field
        [MethodImpl(AggressiveInlining)] public static implicit operator Matrix3x2(MatrixTransform2D self) => self.Matrix;
        [MethodImpl(AggressiveInlining)] public static implicit operator MatrixTransform2D(Matrix3x2 value) => new MatrixTransform2D(value);

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(MatrixTransform2D other) => Matrix.Equals(other.Matrix);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(MatrixTransform2D other) => !Matrix.Equals(other.Matrix);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is MatrixTransform2D other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Matrix);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Matrix\" = {Matrix} }}";

        // Explicit implementation of interfaces by forwarding properties to fields
        Matrix3x2 ITransform2D.Matrix { [MethodImpl(AggressiveInlining)] get => Matrix; }

        // Implemented interface functions

        // Unimplemented interface functions
    }
}
