// Autogenerated file: DO NOT EDIT
// Created on 2025-04-08 12:25:04 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Number: IRealNumber<Number>
    {
        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Number Create() => new Number();

        // Static default implementation
        public static readonly Number Default = default;

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Number other) => Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Number other) => !Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Number other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public static Boolean operator==(Number a, Number b) => a.Equals(b);
        [MethodImpl(AggressiveInlining)] public static Boolean operator!=(Number a, Number b) => !a.Equals(b);
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Value.GetHashCode();
        [MethodImpl(AggressiveInlining)] public override string ToString() => Value.ToString();

        // Explicit implementation of interfaces by forwarding properties to fields

        // IArrayLike predefined functions
        public Integer NumComponents { [MethodImpl(AggressiveInlining)] get => 1; }
        public IArray<Number> Components { [MethodImpl(AggressiveInlining)] get => Intrinsics.MakeArray<Number>(Value); }
        [MethodImpl(AggressiveInlining)] public static Number CreateFromComponents(IArray<Number> numbers) => new Number(numbers[0]);

        [MethodImpl(AggressiveInlining)] public static Number CreateFromComponent(Number x) => new Number(x);

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)]  public _T0 QuarticDerivative<_T0>(_T0 a, _T0 b, _T0 c, _T0 d, _T0 e) where _T0 : INumerical<_T0> => a.Multiply(((Number)4)).Multiply(this.Pow(((Integer)3))).Add(b.Multiply(((Number)3)).Multiply(this.Sqr).Add(c.Multiply(((Number)2)).Multiply(this).Add(d)));
public Angle Turns { [MethodImpl(AggressiveInlining)] get  => this.Multiply(Constants.TwoPi); } 
public Angle Degrees { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)360)).Turns; } 
public Angle Gradians { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)400)).Turns; } 
public Angle ArcMinutes { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)60)).Degrees; } 
public Angle ArcSeconds { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)60)).ArcMinutes; } 
// AMBIGUOUS FUNCTIONS 2
        [MethodImpl(AggressiveInlining)]  public Boolean AlmostEqual(Number y) => this.Subtract(y).Abs.LessThanOrEquals(this.MultiplyEpsilon(y));
// AMBIGUOUS FUNCTIONS 2
        public Boolean AlmostZero { [MethodImpl(AggressiveInlining)] get  => this.Abs.LessThan(Constants.Epsilon); } 
public Boolean AlmostZeroOrOne { [MethodImpl(AggressiveInlining)] get  => this.AlmostEqual(Zero).Or(this.AlmostEqual(One)); } 
// AMBIGUOUS FUNCTIONS 3
        [MethodImpl(AggressiveInlining)]  public Number Average(Number y) => this.Add(y).Half;
// AMBIGUOUS FUNCTIONS 2
        [MethodImpl(AggressiveInlining)]  public Boolean Between(Number a, Number b) => this.GreaterThanOrEquals(a).And(this.LessThanOrEquals(b));
// AMBIGUOUS FUNCTIONS 2
        public Boolean Between01 { [MethodImpl(AggressiveInlining)] get  => this.Between(((Number)0), ((Number)1)); } 
// AMBIGUOUS FUNCTIONS 2
        public Number ClampZeroOne { [MethodImpl(AggressiveInlining)] get  => this.Clamp(Zero, One); } 
// AMBIGUOUS FUNCTIONS 2
        public Number Fract { [MethodImpl(AggressiveInlining)] get  => this.Subtract(this.Floor); } 
// AMBIGUOUS FUNCTIONS 2
        public Number FromOne { [MethodImpl(AggressiveInlining)] get  => ((Number)1).Subtract(this); } 
// AMBIGUOUS FUNCTIONS 2
        [MethodImpl(AggressiveInlining)]  public Number InversePow(Number y) => this.Pow(y.Reciprocal);
// AMBIGUOUS FUNCTIONS 2
        [MethodImpl(AggressiveInlining)]  public Number Lerp(Number b, Number t) => this.Multiply(t.FromOne).Add(b.Multiply(t));
// AMBIGUOUS FUNCTIONS 2
        [MethodImpl(AggressiveInlining)]  public Number MultiplyEpsilon(Number y) => this.Abs.Greater(y.Abs).Multiply(Constants.Epsilon);
// AMBIGUOUS FUNCTIONS 2
        public Number Pow2 { [MethodImpl(AggressiveInlining)] get  => this.Multiply(this); } 
// AMBIGUOUS FUNCTIONS 2
        public Number Pow3 { [MethodImpl(AggressiveInlining)] get  => this.Multiply(this.Multiply(this)); } 
// AMBIGUOUS FUNCTIONS 2
        public Number Pow4 { [MethodImpl(AggressiveInlining)] get  => this.Multiply(this.Multiply(this.Multiply(this))); } 
// AMBIGUOUS FUNCTIONS 2
        public Number Pow5 { [MethodImpl(AggressiveInlining)] get  => this.Multiply(this.Multiply(this.Multiply(this.Multiply(this)))); } 
// AMBIGUOUS FUNCTIONS 2
        public Number Sqr { [MethodImpl(AggressiveInlining)] get  => this.Pow2; } 
// AMBIGUOUS FUNCTIONS 2
        public Number Sqrt { [MethodImpl(AggressiveInlining)] get  => this.SquareRoot; } 
[MethodImpl(AggressiveInlining)]  public _T0 Multiply<_T0>(_T0 x) where _T0 : IScalarArithmetic<_T0> => x.Multiply(this);
[MethodImpl(AggressiveInlining)]  public Number SineWave(Number amplitude, Number frequency, Number phase) => amplitude.Multiply(frequency.Multiply(this.Turns.Sin).Add(phase));
[MethodImpl(AggressiveInlining)]  public Number StaircaseFloor(Integer steps) => this.Multiply(steps).Floor.Divide(steps);
[MethodImpl(AggressiveInlining)]  public Number StaircaseCeiling(Integer steps) => this.Multiply(steps).Ceiling.Divide(steps);
[MethodImpl(AggressiveInlining)]  public Number StaircaseRound(Integer steps) => this.Multiply(steps).Round(((Integer)0)).Divide(steps);
[MethodImpl(AggressiveInlining)]  public Point2D Spiral(Number R, Number r, Number numTurns) => new Vector2(this.Turns.Multiply(numTurns).Cos, this.Turns.Multiply(numTurns).Sin).Multiply(r.Lerp(R, this));
[MethodImpl(AggressiveInlining)]  public Matrix4x4 Multiply(Matrix4x4 value1) => this * value1;
        [MethodImpl(AggressiveInlining)]  public Matrix3x2 Multiply(Matrix3x2 value1) => this * value1;
        [MethodImpl(AggressiveInlining)]  public Vector2 Multiply(Vector2 right) => this * right;
        [MethodImpl(AggressiveInlining)]  public Vector3 Multiply(Vector3 right) => this * right;
        [MethodImpl(AggressiveInlining)]  public Vector4 Multiply(Vector4 right) => this * right;
        [MethodImpl(AggressiveInlining)]  public Vector8 Multiply(Vector8 right) => this * right;
        [MethodImpl(AggressiveInlining)]  public Vector8 Divide(Vector8 right) => this / right;
        [MethodImpl(AggressiveInlining)]  public Number Add(Number b) => this + b;
        [MethodImpl(AggressiveInlining)]  public Number Subtract(Number b) => this - b;
        [MethodImpl(AggressiveInlining)]  public Number Multiply(Number b) => this * b;
        [MethodImpl(AggressiveInlining)]  public Number Divide(Number b) => this / b;
        public Number Negative { [MethodImpl(AggressiveInlining)] get => -this; }
        [MethodImpl(AggressiveInlining)]  public Boolean LessThan(Number b) => this < b;
        [MethodImpl(AggressiveInlining)]  public Boolean LessThanOrEquals(Number b) => this <= b;
        [MethodImpl(AggressiveInlining)]  public Boolean GreaterThan(Number b) => this > b;
        [MethodImpl(AggressiveInlining)]  public Boolean GreaterThanOrEquals(Number b) => this >= b;
        [MethodImpl(AggressiveInlining)]  public Angle Multiply(Angle a) => this * a;
        public Translation3D TranslationX { [MethodImpl(AggressiveInlining)] get  => this.XVector3; } 
public Translation3D TranslationY { [MethodImpl(AggressiveInlining)] get  => this.YVector3; } 
public Translation3D TranslationZ { [MethodImpl(AggressiveInlining)] get  => this.ZVector3; } 
public Scaling3D UniformScaling3D { [MethodImpl(AggressiveInlining)] get  => new Vector3(this); } 
public Vector2 Vector2 { [MethodImpl(AggressiveInlining)] get  => (this, this); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Vector2(Number s) => s.Vector2;
        public Vector2 XVector2 { [MethodImpl(AggressiveInlining)] get  => (this, ((Number)0)); } 
public Vector2 YVector2 { [MethodImpl(AggressiveInlining)] get  => (((Number)0), this); } 
public Vector3 Vector3 { [MethodImpl(AggressiveInlining)] get  => (this, this, this); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Vector3(Number s) => s.Vector3;
        public Vector3 XVector3 { [MethodImpl(AggressiveInlining)] get  => (this, ((Number)0), ((Number)0)); } 
public Vector3 YVector3 { [MethodImpl(AggressiveInlining)] get  => (((Number)0), this, ((Number)0)); } 
public Vector3 ZVector3 { [MethodImpl(AggressiveInlining)] get  => (((Number)0), ((Number)0), this); } 
public Vector4 Vector4 { [MethodImpl(AggressiveInlining)] get  => (this, this, this, this); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Vector4(Number s) => s.Vector4;
        public Vector4 XVector4 { [MethodImpl(AggressiveInlining)] get  => (this, ((Number)0), ((Number)0), ((Number)0)); } 
public Vector4 YVector4 { [MethodImpl(AggressiveInlining)] get  => (((Number)0), this, ((Number)0), ((Number)0)); } 
public Vector4 ZVector4 { [MethodImpl(AggressiveInlining)] get  => (((Number)0), ((Number)0), this, ((Number)0)); } 
public Vector4 WVector4 { [MethodImpl(AggressiveInlining)] get  => (((Number)0), ((Number)0), ((Number)0), this); } 
public Vector8 Vector8 { [MethodImpl(AggressiveInlining)] get  => (this, this, this, this, this, this, this, this); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Vector8(Number s) => s.Vector8;
        [MethodImpl(AggressiveInlining)]  public Number Barycentric(Number v2, Number v3, Vector2 uv) => this.Add(v2.Subtract(this)).Multiply(uv.X).Add(v3.Subtract(this).Multiply(uv.Y));
[MethodImpl(AggressiveInlining)]  public Number Linear(Number b, Number x) => this.Multiply(x).Add(b);
[MethodImpl(AggressiveInlining)]  public Number Quadratic(Number b, Number c, Number x) => this.Multiply(x.Sqr).Add(b.Multiply(x).Add(c));
[MethodImpl(AggressiveInlining)]  public Number Cubic(Number b, Number c, Number d, Number x) => this.Multiply(x.Pow3).Add(b.Multiply(x.Sqr).Add(c.Multiply(x).Add(d)));
[MethodImpl(AggressiveInlining)]  public Number Quartic(Number b, Number c, Number d, Number e, Number x) => this.Multiply(x.Pow(((Integer)4))).Add(b.Multiply(x.Pow3).Add(c.Multiply(x.Sqr).Add(d.Multiply(x).Add(e))));
[MethodImpl(AggressiveInlining)]  public Number LinearDerivative(Number b, Number x) => this;
[MethodImpl(AggressiveInlining)]  public Number LinearSecondDerivative(Number b, Number x) => default;
[MethodImpl(AggressiveInlining)]  public Number QuadraticDerivative(Number b, Number c, Number x) => this.Multiply(((Number)2)).Multiply(x).Add(b);
[MethodImpl(AggressiveInlining)]  public Number QuadraticSecondDerivative(Number b, Number c, Number x) => this.Multiply(((Number)2));
[MethodImpl(AggressiveInlining)]  public Number CubicDerivative(Number b, Number c, Number d, Number x) => this.Multiply(((Number)3)).Multiply(x.Sqr).Add(b.Multiply(((Number)2)).Multiply(x).Add(c));
[MethodImpl(AggressiveInlining)]  public Number CubicSecondDerivative(Number b, Number c, Number d, Number x) => this.Multiply(((Number)6)).Multiply(x).Add(b.Multiply(((Number)2)));
[MethodImpl(AggressiveInlining)]  public Number QuarticSecondDerivative(Number b, Number c, Number d, Number e, Number x) => this.Multiply(((Number)12)).Multiply(x.Sqr).Add(b.Multiply(((Number)6)).Multiply(x).Add(c.Multiply(((Number)2))));
[MethodImpl(AggressiveInlining)]  public Number CubicBezier(Number b, Number c, Number d, Number t) => this.Multiply(((Number)1).Subtract(t).Pow3).Add(b.Multiply(((Number)3).Multiply(((Number)1).Subtract(t).Sqr.Multiply(t))).Add(c.Multiply(((Number)3).Multiply(((Number)1).Subtract(t).Multiply(t.Sqr))).Add(d.Multiply(t.Pow3))));
[MethodImpl(AggressiveInlining)]  public Number CubicBezierDerivative(Number b, Number c, Number d, Number t) => b.Subtract(this).Multiply(((Number)3).Multiply(((Number)1).Subtract(t).Sqr)).Add(c.Subtract(b).Multiply(((Number)6).Multiply(((Number)1).Subtract(t).Multiply(t))).Add(d.Subtract(c).Multiply(((Number)3).Multiply(t.Sqr))));
[MethodImpl(AggressiveInlining)]  public Number CubicBezierSecondDerivative(Number b, Number c, Number d, Number t) => c.Subtract(b.Multiply(((Number)2)).Add(this)).Multiply(((Number)6).Multiply(((Number)1).Subtract(t))).Add(d.Subtract(c.Multiply(((Number)2)).Add(b)).Multiply(((Number)6).Multiply(t)));
[MethodImpl(AggressiveInlining)]  public Number QuadraticBezier(Number b, Number c, Number t) => this.Multiply(((Number)1).Subtract(t).Sqr).Add(b.Multiply(((Number)2).Multiply(((Number)1).Subtract(t).Multiply(t))).Add(c.Multiply(t.Sqr)));
[MethodImpl(AggressiveInlining)]  public Number QuadraticBezierDerivative(Number b, Number c, Number t) => b.Subtract(this).Multiply(((Number)2).Multiply(((Number)1).Subtract(t))).Add(c.Subtract(b).Multiply(((Number)2).Multiply(t)));
[MethodImpl(AggressiveInlining)]  public Number QuadraticBezierSecondDerivative(Number b, Number c, Number t) => ((Number)2).Multiply(this.Subtract(b.Multiply(((Number)2)).Add(c)));
[MethodImpl(AggressiveInlining)]  public Number Hermite(Number p1, Number m0, Number m1, Number t) => this.Multiply(((Number)2).Multiply(t.Pow3).Subtract(((Number)3).Multiply(t.Sqr).Add(((Number)1)))).Add(m0.Multiply(t.Pow3.Subtract(((Number)2).Multiply(t.Sqr).Add(t))).Add(p1.Multiply(((Number)2).Multiply(t.Pow3).Add(((Number)3).Multiply(t.Sqr)).Negative).Add(m1.Multiply(t.Pow3.Subtract(t.Sqr)))));
[MethodImpl(AggressiveInlining)]  public Number HermiteDerivative(Number p1, Number m0, Number m1, Number t) => this.Multiply(((Number)6).Multiply(t.Sqr).Subtract(((Number)6).Multiply(t))).Add(m0.Multiply(((Number)3).Multiply(t.Sqr).Subtract(((Number)4).Multiply(t).Add(((Number)1)))).Add(p1.Multiply(((Number)6).Multiply(t.Sqr).Add(((Number)6).Multiply(t)).Negative).Add(m1.Multiply(((Number)3).Multiply(t.Sqr).Subtract(((Number)2).Multiply(t))))));
[MethodImpl(AggressiveInlining)]  public Number CatmullRom(Number p1, Number p2, Number p3, Number t) => ((Number)0.5).Multiply(p1.Multiply(((Number)2)).Add(p2.Subtract(this).Multiply(t).Add(this.Multiply(((Number)2)).Subtract(p1.Multiply(((Number)5)).Add(p2.Multiply(((Number)4)).Subtract(p3))).Multiply(t.Sqr).Add(this.Add(p1.Multiply(((Number)3)).Subtract(p2.Multiply(((Number)3)).Add(p3))).Negative.Multiply(t.Pow3)))));
[MethodImpl(AggressiveInlining)]  public Number CatmullRomDerivative(Number p1, Number p2, Number p3, Number t) => ((Number)0.5).Multiply(p2.Subtract(this).Add(((Number)2).Multiply(this.Multiply(((Number)2)).Subtract(p1.Multiply(((Number)5)).Add(p2.Multiply(((Number)4)).Subtract(p3))).Multiply(t)).Add(((Number)3).Multiply(this.Add(p1.Multiply(((Number)3)).Subtract(p2.Multiply(((Number)3)).Add(p3))).Negative.Multiply(t.Sqr)))));
public Number SmoothStep { [MethodImpl(AggressiveInlining)] get  => this.Sqr.Multiply(this.Twice.Add(((Number)3)).Negative); } 
public Number SmootherStep { [MethodImpl(AggressiveInlining)] get  => this.Pow3.Multiply(this.Multiply(((Number)6)).Subtract(((Number)15))).Add(((Number)10)); } 
public static Number Zero { [MethodImpl(AggressiveInlining)] get  => Number.CreateFromComponent(((Number)0)); } 
public static Number One { [MethodImpl(AggressiveInlining)] get  => Number.CreateFromComponent(((Number)1)); } 
public static Number MinValue { [MethodImpl(AggressiveInlining)] get  => float.MinValue; } 
public static Number MaxValue { [MethodImpl(AggressiveInlining)] get  => float.MaxValue; } 
[MethodImpl(AggressiveInlining)]  public Number Reduce(Number initial, System.Func<Number, Number, Number> f) => this.Components.Reduce(initial, f);
public Number MinComponent { [MethodImpl(AggressiveInlining)] get  => this.Reduce(this.At(((Integer)0)), (a, b)  => a.Min(b)); } 
public Number MaxComponent { [MethodImpl(AggressiveInlining)] get  => this.Reduce(this.At(((Integer)0)), (a, b)  => a.Max(b)); } 
public Number SumComponents { [MethodImpl(AggressiveInlining)] get  => this.Reduce(((Number)0), (a, b)  => a.Add(b)); } 
public Number SumSqrComponents { [MethodImpl(AggressiveInlining)] get  => this.Reduce(((Number)0), (a, b)  => a.Add(b.Multiply(b))); } 
public Number AvgComponent { [MethodImpl(AggressiveInlining)] get  => this.SumComponents.Divide(this.NumComponents); } 
public Number Magnitude { [MethodImpl(AggressiveInlining)] get  => this.MagnitudeSquared.Sqrt; } 
public Number MagnitudeSquared { [MethodImpl(AggressiveInlining)] get  => this.SumSqrComponents.Divide(this.NumComponents); } 
[MethodImpl(AggressiveInlining)]  public IArray<Number> Sample(Number b, Integer n){
            var _var182 = b;
            {
                var _var181 = this;
                return n.LinearSpace.Map((i)  => _var181.Lerp(_var182, i));
            }
        }

public Number Half { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)2)); } 
public Number Quarter { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)4)); } 
public Number Eight { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)8)); } 
public Number Sixteenth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)16)); } 
public Number Tenth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)10)); } 
public Number Twice { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)2)); } 
public Number Hundred { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)100)); } 
public Number Thousand { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)1000)); } 
public Number Million { [MethodImpl(AggressiveInlining)] get  => this.Thousand.Thousand; } 
public Number Billion { [MethodImpl(AggressiveInlining)] get  => this.Thousand.Million; } 
public Number Hundredth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)100)); } 
public Number Thousandth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)1000)); } 
public Number Millionth { [MethodImpl(AggressiveInlining)] get  => this.Thousandth.Thousandth; } 
public Number Billionth { [MethodImpl(AggressiveInlining)] get  => this.Thousandth.Millionth; } 
[MethodImpl(AggressiveInlining)]  public Number At(Integer n) => this.Components.At(n);
public Number this[Integer n] { [MethodImpl(AggressiveInlining)]  get => At(n); }
        [MethodImpl(AggressiveInlining)]  public Number MapComponents(System.Func<Number, Number> f) => Number.CreateFromComponents(this.Components.Map(f));
[MethodImpl(AggressiveInlining)]  public Number ZipComponents(Number b, System.Func<Number, Number, Number> f) => Number.CreateFromComponents(this.Components.Zip(b.Components, f));
[MethodImpl(AggressiveInlining)]  public Number ZipComponents(Number b, Number c, System.Func<Number, Number, Number, Number> f) => Number.CreateFromComponents(this.Components.Zip(b.Components, c.Components, f));
[MethodImpl(AggressiveInlining)]  public Boolean AllZipComponents(Number b, System.Func<Number, Number, Boolean> f) => this.Components.Zip(b.Components, f).All((x)  => x);
[MethodImpl(AggressiveInlining)]  public Boolean AllZipComponents(Number b, Number c, System.Func<Number, Number, Number, Boolean> f) => this.Components.Zip(b.Components, c.Components, f).All((x)  => x);
[MethodImpl(AggressiveInlining)]  public Boolean AnyZipComponents(Number b, System.Func<Number, Number, Boolean> f) => this.Components.Zip(b.Components, f).Any((x)  => x);
[MethodImpl(AggressiveInlining)]  public Boolean AnyZipComponents(Number b, Number c, System.Func<Number, Number, Number, Boolean> f) => this.Components.Zip(b.Components, c.Components, f).Any((x)  => x);
[MethodImpl(AggressiveInlining)]  public Boolean AllComponents(System.Func<Number, Boolean> predicate) => this.Components.All(predicate);
[MethodImpl(AggressiveInlining)]  public Boolean AnyComponent(System.Func<Number, Boolean> predicate) => this.Components.Any(predicate);
[MethodImpl(AggressiveInlining)]  public Number Lesser(Number b) => this.LessThanOrEquals(b) ? this : b;
[MethodImpl(AggressiveInlining)]  public Number Greater(Number b) => this.GreaterThanOrEquals(b) ? this : b;

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)]  public Number Modulo(Number b) => this % b;
    }
}
