// Autogenerated file: DO NOT EDIT
// Created on 2025-04-07 4:05:19 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct PointArray3D: IPointArray3D<PointArray3D>
    {
        // Fields
        [DataMember] public readonly IArray<Point3D> Points;

        // With functions 
        [MethodImpl(AggressiveInlining)] public PointArray3D WithPoints(IArray<Point3D> points) => new PointArray3D(points);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public PointArray3D(IArray<Point3D> points) { Points = points; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static PointArray3D Create(IArray<Point3D> points) => new PointArray3D(points);

        // Static default implementation
        public static readonly PointArray3D Default = default;

        // Implicit converters to/from single field

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(PointArray3D other) => Points.Equals(other.Points);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(PointArray3D other) => !Points.Equals(other.Points);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is PointArray3D other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Points);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Points\" = {Points} }}";

        // Explicit implementation of interfaces by forwarding properties to fields
        IArray<Point3D> IPointGeometry3D<PointArray3D>.Points { [MethodImpl(AggressiveInlining)] get => Points; }

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)]  public PointArray3D Deform(System.Func<Point3D, Point3D> f) => new PointArray3D(this.Points.Map(f));
public IArray<Integer> Indices { [MethodImpl(AggressiveInlining)] get  => this.Points.Indices; } 
[MethodImpl(AggressiveInlining)]  public PointArray3D Deform<_T0>(_T0 t) where _T0 : ITransform3D{
            var _var150 = t;
            return this.Deform((v)  => _var150.Transform(v));
        }

[MethodImpl(AggressiveInlining)]  public PointArray3D Scale(Vector3 v){
            var _var151 = v;
            return this.Deform((p)  => p.Vector3.Multiply(_var151));
        }

[MethodImpl(AggressiveInlining)]  public PointArray3D Scale(Number s) => this.Scale((s, s, s));
[MethodImpl(AggressiveInlining)]  public PointArray3D ScaleX(Number s) => this.Scale((s, ((Integer)1), ((Integer)1)));
[MethodImpl(AggressiveInlining)]  public PointArray3D ScaleY(Number s) => this.Scale((((Integer)1), s, ((Integer)1)));
[MethodImpl(AggressiveInlining)]  public PointArray3D ScaleZ(Number s) => this.Scale((((Integer)1), ((Integer)1), s));
[MethodImpl(AggressiveInlining)]  public PointArray3D Rotate(Quaternion q){
            var _var152 = q;
            return this.Deform((v)  => _var152.Transform(v));
        }

[MethodImpl(AggressiveInlining)]  public PointArray3D RotateX(Angle a) => this.Rotate(a.RotateX);
[MethodImpl(AggressiveInlining)]  public PointArray3D RotateY(Angle a) => this.Rotate(a.RotateY);
[MethodImpl(AggressiveInlining)]  public PointArray3D RotateZ(Angle a) => this.Rotate(a.RotateZ);
[MethodImpl(AggressiveInlining)]  public PointArray3D Translate(Vector3 v){
            var _var153 = v;
            return this.Deform((p)  => p.Add(_var153));
        }

[MethodImpl(AggressiveInlining)]  public PointArray3D TranslateX(Number s) => this.Translate(s.XVector3);
[MethodImpl(AggressiveInlining)]  public PointArray3D TranslateY(Number s) => this.Translate(s.YVector3);
[MethodImpl(AggressiveInlining)]  public PointArray3D TranslateZ(Number s) => this.Translate(s.ZVector3);

        // Unimplemented interface functions
        public Bounds3D Bounds => throw new NotImplementedException();
}
}
