// Autogenerated file: DO NOT EDIT
// Created on 2025-03-18 2:15:23 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct QuadMesh3D: IQuadMesh3D
    {
        // Fields
        [DataMember] public readonly IArray<Vector3> Points;
        [DataMember] public readonly IArray<Integer> Indices;

        // With functions 
        [MethodImpl(AggressiveInlining)] public QuadMesh3D WithPoints(IArray<Vector3> points) => new QuadMesh3D(points, Indices);
        [MethodImpl(AggressiveInlining)] public QuadMesh3D WithIndices(IArray<Integer> indices) => new QuadMesh3D(Points, indices);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public QuadMesh3D(IArray<Vector3> points, IArray<Integer> indices) { Points = points; Indices = indices; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static QuadMesh3D Create(IArray<Vector3> points, IArray<Integer> indices) => new QuadMesh3D(points, indices);

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (IArray<Vector3>, IArray<Integer>)(QuadMesh3D self) => (self.Points, self.Indices);
        [MethodImpl(AggressiveInlining)] public static implicit operator QuadMesh3D((IArray<Vector3>, IArray<Integer>) value) => new(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out IArray<Vector3> points, out IArray<Integer> indices) { points = Points; indices = Indices;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(QuadMesh3D other) => Points.Equals(other.Points) && Indices.Equals(other.Indices);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(QuadMesh3D other) => !Points.Equals(other.Points) && Indices.Equals(other.Indices);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is QuadMesh3D other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Points, Indices);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Points\" = {Points}, \"Indices\" = {Indices} }}";

        // Explicit implementation of interfaces by forwarding properties to fields
        IArray<Integer> IIndexedGeometry.Indices { [MethodImpl(AggressiveInlining)] get => Indices; }

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)]  public QuadMesh3D Deform(System.Func<Vector3, Vector3> f) => (this.Points.Map(f), this.Indices);
public LineMesh3D LineMesh3D { [MethodImpl(AggressiveInlining)] get  => (this.Points, this.FaceIndices.FlatMap((a)  => Intrinsics.MakeArray(a.At(((Integer)0)), a.At(((Integer)1)), a.At(((Integer)1)), a.At(((Integer)2)), a.At(((Integer)2)), a.At(((Integer)3)), a.At(((Integer)3)), a.At(((Integer)0))))); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator LineMesh3D(QuadMesh3D g) => g.LineMesh3D;
        public TriangleMesh3D TriangleMesh3D { [MethodImpl(AggressiveInlining)] get  => (this.Points, this.FaceIndices.FlatMap((a)  => Intrinsics.MakeArray(a.At(((Integer)0)), a.At(((Integer)1)), a.At(((Integer)2)), a.At(((Integer)2)), a.At(((Integer)3)), a.At(((Integer)0))))); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator TriangleMesh3D(QuadMesh3D g) => g.TriangleMesh3D;
        public _T0 Faces<_T0> where _T0 : IArray<_T0> { [MethodImpl(AggressiveInlining)] get  => this.Quads; } 
public _T0 Quads<_T0> where _T0 : IArray<_T0> { [MethodImpl(AggressiveInlining)] get  => this.AllFaceVertices.Map((xs)  => new Quad3D(xs.At(((Integer)0)), xs.At(((Integer)1)), xs.At(((Integer)2)), xs.At(((Integer)3)))); } 
[MethodImpl(AggressiveInlining)]  public Vector3 Vertex(Integer n) => this.Points.At(this.Indices.At(n));
[MethodImpl(AggressiveInlining)]  public _T0 FaceVertices<_T0>(Integer f) where _T0 : IArray<_T0>{
            var _var158 = this;
            return this.FaceIndices.At(f).Map((i)  => _var158.Vertex(i));
        }

public _T0 AllFaceVertices<_T0> where _T0 : IArray2D<_T0> { [MethodImpl(AggressiveInlining)] get {
            var _var159 = this;
            return this.AllFaceIndices.Map((x)  => _var159.Vertex(x));
        }
         } 
[MethodImpl(AggressiveInlining)]  public _T1 Vertices<_T0, _T1>(_T0 xs) where _T0 : IArray<_T0>; where _T1 : IArray<_T1>{
            var _var160 = this;
            return xs.Map((i)  => _var160.Vertex(i));
        }

public _T0 AllVertices<_T0> where _T0 : IArray<_T0> { [MethodImpl(AggressiveInlining)] get  => this.Vertices(this.Indices); } 
public Integer NumPrimitives { [MethodImpl(AggressiveInlining)] get  => this.Indices.Count.Divide(this.PrimitiveSize); } 
public Integer NumFaces { [MethodImpl(AggressiveInlining)] get  => this.NumPrimitives; } 
public _T0 AllFaceIndices<_T0> where _T0 : IArray2D<_T0> { [MethodImpl(AggressiveInlining)] get  => this.Indices.Slices(this.PrimitiveSize); } 
public Integer PrimitiveSize { [MethodImpl(AggressiveInlining)] get  => ((Integer)4); } 
public _T0 FaceIndices<_T0> where _T0 : IArray<_T0> { [MethodImpl(AggressiveInlining)] get  => this.Indices.Integer4Array; } 

        // Unimplemented concept functions
        public _T0 Corners<_T0> where _T0 : IArray<_T0> => throw new NotImplementedException();
}
}
