// Autogenerated file: DO NOT EDIT
// Created on 2025-03-09 8:08:08 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
public partial struct QuadraticBezier2D: IArray<Vector2>, IOpenCurve2D
{
    // Fields
    [DataMember] public readonly Vector2 A;
    [DataMember] public readonly Vector2 B;
    [DataMember] public readonly Vector2 C;

    // With functions 
    [MethodImpl(AggressiveInlining)] public QuadraticBezier2D WithA(Vector2 a) => new QuadraticBezier2D(a, B, C);
    [MethodImpl(AggressiveInlining)] public QuadraticBezier2D WithB(Vector2 b) => new QuadraticBezier2D(A, b, C);
    [MethodImpl(AggressiveInlining)] public QuadraticBezier2D WithC(Vector2 c) => new QuadraticBezier2D(A, B, c);

    // Regular Constructor
    [MethodImpl(AggressiveInlining)] public QuadraticBezier2D(Vector2 a, Vector2 b, Vector2 c) { A = a; B = b; C = c; }

    // Static factory function
    [MethodImpl(AggressiveInlining)] public static QuadraticBezier2D Create(Vector2 a, Vector2 b, Vector2 c) => new QuadraticBezier2D(a, b, c);

    // Implicit converters to/from value-tuples and deconstructor
    [MethodImpl(AggressiveInlining)] public static implicit operator (Vector2, Vector2, Vector2)(QuadraticBezier2D self) => (self.A, self.B, self.C);
    [MethodImpl(AggressiveInlining)] public static implicit operator QuadraticBezier2D((Vector2, Vector2, Vector2) value) => new(value.Item1, value.Item2, value.Item3);
    [MethodImpl(AggressiveInlining)] public void Deconstruct(out Vector2 a, out Vector2 b, out Vector2 c) { a = A; b = B; c = C;  }

    // Object virtual function overrides: Equals, GetHashCode, ToString
    [MethodImpl(AggressiveInlining)] public Boolean Equals(QuadraticBezier2D other) => A.Equals(other.A) && B.Equals(other.B) && C.Equals(other.C);
    [MethodImpl(AggressiveInlining)] public Boolean NotEquals(QuadraticBezier2D other) => !A.Equals(other.A) && B.Equals(other.B) && C.Equals(other.C);
    [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is QuadraticBezier2D other ? Equals(other) : false;
    [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(A, B, C);
    [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"A\" = {A}, \"B\" = {B}, \"C\" = {C} }}";

    // Explicit implementation of interfaces by forwarding properties to fields

    // Array predefined functions
    [MethodImpl(AggressiveInlining)] public QuadraticBezier2D(IReadOnlyList<Vector2> xs) : this(xs[0], xs[1], xs[2]) { }
    [MethodImpl(AggressiveInlining)] public QuadraticBezier2D(Vector2[] xs) : this(xs[0], xs[1], xs[2]) { }
    [MethodImpl(AggressiveInlining)] public static QuadraticBezier2D Create(IReadOnlyList<Vector2> xs) => new QuadraticBezier2D(xs);
    // Implementation of IReadOnlyList
    [MethodImpl(AggressiveInlining)] public System.Collections.Generic.IEnumerator<Vector2> GetEnumerator() => new ArrayEnumerator<Vector2>(this);
    [MethodImpl(AggressiveInlining)] System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
    Vector2 System.Collections.Generic.IReadOnlyList<Vector2>.this[int n] { [MethodImpl(AggressiveInlining)] get => At(n); }
    int System.Collections.Generic.IReadOnlyCollection<Vector2>.Count { [MethodImpl(AggressiveInlining)] get => this.Count; }

    // Implemented concept functions and type functions
    [MethodImpl(AggressiveInlining)]  public Vector2 Eval(Number t) => t.QuadraticBezier(this.A, this.B, this.C);
[MethodImpl(AggressiveInlining)]  public IArray<Vector2> Sample(Integer numPoints){
    var _var77 = this;
    return numPoints.LinearSpace.Map((x) =>  => _var77.Eval(x);
;
}

[MethodImpl(AggressiveInlining)]  public PolyLine2D ToPolyLine2D(Integer numPoints) => (this.Sample(numPoints), this.Closed);
[MethodImpl(AggressiveInlining)]  public Procedural<Number, TR> Combine<TR>(QuadraticBezier2D b, System.Func<TR, TR, TR> f){
    var _var80 = b;
    {
        var _var79 = this;
        {
            var _var78 = f;
            return (x) =>  => _var78.Invoke(_var79.Eval(x), _var80.Eval(x));
;
        }
    }
}

[MethodImpl(AggressiveInlining)]  public Procedural<TR, Vector2> MapDomain<T0, TR>(System.Func<T0, TR> f){
    var _var82 = f;
    {
        var _var81 = this;
        return new Procedural<$TIn2,$TOut>((x) =>  => _var81.Eval(_var82.Invoke(x));
;
    }
}

public System.Func<Number, Vector2> Function { [MethodImpl(AggressiveInlining)] get {
    var _var83 = this;
    return (x) =>  => _var83.Eval(x);
;
}
 } 
[MethodImpl(AggressiveInlining)]  public Procedural<Number, Vector2> Compose(QuadraticBezier2D b){
    var _var85 = this;
    {
        var _var84 = b;
        return new Procedural<$TIn2,$TOut>((x) =>  => _var84.Eval(_var85.Eval(x));
;
    }
}

[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, TR> Combine<TR>(QuadraticBezier2D b, System.Func<TR, TR, TR> f){
    var _var88 = b;
    {
        var _var87 = this;
        {
            var _var86 = f;
            return (x) =>  => _var86.Invoke(_var87.Eval(x), _var88.Eval(x));
;
        }
    }
}

[MethodImpl(AggressiveInlining)]  public Procedural<TR, Number> MapDomain<T0, TR>(System.Func<T0, TR> f){
    var _var90 = f;
    {
        var _var89 = this;
        return new Procedural<$TIn2,$TOut>((x) =>  => _var89.Eval(_var90.Invoke(x));
;
    }
}

public System.Func<Vector2, Number> Function { [MethodImpl(AggressiveInlining)] get {
    var _var91 = this;
    return (x) =>  => _var91.Eval(x);
;
}
 } 
[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, Number> Compose(QuadraticBezier2D b){
    var _var93 = this;
    {
        var _var92 = b;
        return new Procedural<$TIn2,$TOut>((x) =>  => _var92.Eval(_var93.Eval(x));
;
    }
}

[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, $TOut> Union(QuadraticBezier2D b) => this.Combine(b, (a, b) =>  => a.Max(b);

[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, $TOut> Intersection(QuadraticBezier2D b) => this.Combine(b, (a, b) =>  => a.Min(b);

[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, $TOut> Difference(QuadraticBezier2D b) => this.Combine(b, (a, b) =>  => a.Max(b.Negative);

public Procedural<Vector2, Number> Inverse { [MethodImpl(AggressiveInlining)] get  => this.Map((x) =>  => x.Negative;
 } 
[MethodImpl(AggressiveInlining)]  public Procedural<Vector2, Boolean> Threshold(Number threshold){
    var _var94 = threshold;
    return this.Map((x) =>  => x.GreaterThanOrEquals(_var94);
;
}

public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => ((Boolean)false); } 

    // Unimplemented concept functions
    public Integer Count { [MethodImpl(AggressiveInlining)] get => 3; }
    [MethodImpl(AggressiveInlining)]  public Vector2 At(Integer n) => n == 0 ? A : n == 1 ? B : n == 2 ? C : throw new System.IndexOutOfRangeException();
    public Vector2 this[Integer n] { [MethodImpl(AggressiveInlining)] get => At(n); }
    [MethodImpl(AggressiveInlining)]  public Number Distance(Vector2 p) => throw new NotImplementedException();
[MethodImpl(AggressiveInlining)]  public Number Eval(Vector2 t) => throw new NotImplementedException();
}
Plato.CSharpWriter.CSharpConcreteTypeWriter}
