// Autogenerated file: DO NOT EDIT
// Created on 2025-03-14 12:36:59 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct QuadArray3D: IQuadArray3D
    {
        // Fields
        [DataMember] public readonly IArray<Quad3D> Quads;

        // With functions 
        [MethodImpl(AggressiveInlining)] public QuadArray3D WithQuads(IArray<Quad3D> quads) => new QuadArray3D(quads);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public QuadArray3D(IArray<Quad3D> quads) { Quads = quads; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static QuadArray3D Create(IArray<Quad3D> quads) => new QuadArray3D(quads);

        // Implicit converters to/from single field

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(QuadArray3D other) => Quads.Equals(other.Quads);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(QuadArray3D other) => !Quads.Equals(other.Quads);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is QuadArray3D other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Quads);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Quads\" = {Quads} }}";

        // Explicit implementation of interfaces by forwarding properties to fields
        IArray<Quad3D> IQuadGeometry3D.Quads { [MethodImpl(AggressiveInlining)] get => Quads; }

        // Implemented interface functions
        // Deform(QuadArray3D, Function1<Vector3, Vector3>):QuadArray3D; [Self=QuadArray3D;]; <>
        [MethodImpl(AggressiveInlining)]  public QuadArray3D Deform(System.Func<Vector3, Vector3> f){
            var _var180 = f;
            return new QuadArray3D(this.Quads.Map((q)  => q.Deform(_var180)));
        }

// Indices(QuadArray3D):_T0; [IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <_T0:IArray<Integer>>
        public _T0 Indices<_T0> { [MethodImpl(AggressiveInlining)] get  => this.Points.Indices(); } 
// TriangleArray3D(QuadArray3D):TriangleArray3D; [IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <>
        public TriangleArray3D TriangleArray3D { [MethodImpl(AggressiveInlining)] get  => new TriangleArray3D(this.Triangles); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator TriangleArray3D(QuadArray3D q) => q.TriangleArray3D;
        // QuadMesh3D(QuadArray3D):QuadMesh3D; [IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <>
        public QuadMesh3D QuadMesh3D { [MethodImpl(AggressiveInlining)] get  => (this.Points, this.Points.Indices()); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator QuadMesh3D(QuadArray3D self) => self.QuadMesh3D;
        // TriangleMesh3D(QuadArray3D):TriangleMesh3D; [IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <>
        public TriangleMesh3D TriangleMesh3D { [MethodImpl(AggressiveInlining)] get  => this.TriangleArray3D; } 
[MethodImpl(AggressiveInlining)]  public static implicit operator TriangleMesh3D(QuadArray3D g) => g.TriangleMesh3D;
        // Points(QuadArray3D):_T0; [IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <_T0:IArray<Vector3>>
        public _T0 Points<_T0> { [MethodImpl(AggressiveInlining)] get  => this.Quads.FlatMap((x)  => x.Points); } 
// Lines(QuadArray3D):_T0; [IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <_T0:IArray<Line3D>>
        public _T0 Lines<_T0> { [MethodImpl(AggressiveInlining)] get  => this.Quads.FlatMap((x)  => x.Lines); } 
// Triangles(QuadArray3D):_T0; [IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <_T0:IArray<Triangle3D>>
        public _T0 Triangles<_T0> { [MethodImpl(AggressiveInlining)] get  => this.Quads.FlatMap((x)  => x.Triangles); } 
// LineMesh3D(QuadArray3D):LineMesh3D; [IQuadMesh3D=QuadArray3D;IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <>
        public LineMesh3D LineMesh3D { [MethodImpl(AggressiveInlining)] get  => (this.Points, this.FaceIndices.FlatMap((a)  => Intrinsics.MakeArray(a.At(((Integer)0)), a.At(((Integer)1)), a.At(((Integer)1)), a.At(((Integer)2)), a.At(((Integer)2)), a.At(((Integer)3)), a.At(((Integer)3)), a.At(((Integer)0))))); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator LineMesh3D(QuadArray3D g) => g.LineMesh3D;
        // Faces(QuadArray3D):_T0; [IQuadMesh3D=QuadArray3D;IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <_T0:IArray<Quad3D>>
        public _T0 Faces<_T0> { [MethodImpl(AggressiveInlining)] get  => this.Quads; } 
// Vertex(QuadArray3D, Integer):Vector3; [IIndexedGeometry3D=QuadArray3D;IQuadMesh3D=QuadArray3D;IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <>
        [MethodImpl(AggressiveInlining)]  public Vector3 Vertex(Integer n) => this.Points.At(this.Indices.At(n));
// FaceVertices(QuadArray3D, Integer):_T0; [IIndexedGeometry3D=QuadArray3D;IQuadMesh3D=QuadArray3D;IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <_T0:IArray<Vector3>>
        [MethodImpl(AggressiveInlining)]  public _T0 FaceVertices<_T0>(Integer f){
            var _var181 = this;
            return this.FaceIndices.At(f).Map((i)  => _var181.Vertex(i));
        }

// AllFaceVertices(QuadArray3D):_T0; [IIndexedGeometry3D=QuadArray3D;IQuadMesh3D=QuadArray3D;IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <_T0:IArray2D<Vector3>>
        public _T0 AllFaceVertices<_T0> { [MethodImpl(AggressiveInlining)] get {
            var _var182 = this;
            return this.AllFaceIndices.Map((x)  => _var182.Vertex(x));
        }
         } 
// Vertices(QuadArray3D, _T0):_T1; [IIndexedGeometry3D=QuadArray3D;IQuadMesh3D=QuadArray3D;IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <_T0:IArray<Integer>, _T1:IArray<Vector3>>
        [MethodImpl(AggressiveInlining)]  public _T1 Vertices<_T0, _T1>(_T0 xs){
            var _var183 = this;
            return xs.Map((i)  => _var183.Vertex(i));
        }

// AllVertices(QuadArray3D):_T0; [IIndexedGeometry3D=QuadArray3D;IQuadMesh3D=QuadArray3D;IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <_T0:IArray<Vector3>>
        public _T0 AllVertices<_T0> { [MethodImpl(AggressiveInlining)] get  => this.Vertices(this.Indices); } 
// NumPrimitives(QuadArray3D):Integer; [IIndexedGeometry=QuadArray3D;IIndexedGeometry3D=QuadArray3D;IQuadMesh3D=QuadArray3D;IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <>
        public Integer NumPrimitives { [MethodImpl(AggressiveInlining)] get  => this.Indices.Count.Divide(this.PrimitiveSize); } 
// NumFaces(QuadArray3D):Integer; [IIndexedGeometry=QuadArray3D;IIndexedGeometry3D=QuadArray3D;IQuadMesh3D=QuadArray3D;IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <>
        public Integer NumFaces { [MethodImpl(AggressiveInlining)] get  => this.NumPrimitives; } 
// AllFaceIndices(QuadArray3D):_T0; [IIndexedGeometry=QuadArray3D;IIndexedGeometry3D=QuadArray3D;IQuadMesh3D=QuadArray3D;IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <_T0:IArray2D<Integer>>
        public _T0 AllFaceIndices<_T0> { [MethodImpl(AggressiveInlining)] get  => this.Indices.Slices(this.PrimitiveSize); } 
// PrimitiveSize(QuadArray3D):Integer; [IQuadGeometry=QuadArray3D;IQuadGeometry3D=QuadArray3D;IQuadMesh3D=QuadArray3D;IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <>
        public Integer PrimitiveSize { [MethodImpl(AggressiveInlining)] get  => ((Integer)4); } 
// FaceIndices(QuadArray3D):_T0; [IQuadGeometry=QuadArray3D;IQuadGeometry3D=QuadArray3D;IQuadMesh3D=QuadArray3D;IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <_T0:IArray<Integer4>>
        public _T0 FaceIndices<_T0> { [MethodImpl(AggressiveInlining)] get  => this.Indices.Integer4Array; } 

        // Unimplemented concept functions
        // Corners(QuadArray3D):_T0; [IPrimitiveGeometry3D=QuadArray3D;IQuadGeometry3D=QuadArray3D;IQuadMesh3D=QuadArray3D;IQuadArray3D=QuadArray3D;Self=QuadArray3D;]; <_T0:IArray<Vector3>>
        public _T0 Corners<_T0> => throw new NotImplementedException();
}
}
