// Autogenerated file: DO NOT EDIT
// Created on 2025-03-18 2:15:23 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Quad3D: IPolygon3D, IDeformable3D<Quad3D>
    {
        // Fields
        [DataMember] public readonly Vector3 A;
        [DataMember] public readonly Vector3 B;
        [DataMember] public readonly Vector3 C;
        [DataMember] public readonly Vector3 D;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Quad3D WithA(Vector3 a) => new Quad3D(a, B, C, D);
        [MethodImpl(AggressiveInlining)] public Quad3D WithB(Vector3 b) => new Quad3D(A, b, C, D);
        [MethodImpl(AggressiveInlining)] public Quad3D WithC(Vector3 c) => new Quad3D(A, B, c, D);
        [MethodImpl(AggressiveInlining)] public Quad3D WithD(Vector3 d) => new Quad3D(A, B, C, d);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Quad3D(Vector3 a, Vector3 b, Vector3 c, Vector3 d) { A = a; B = b; C = c; D = d; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Quad3D Create(Vector3 a, Vector3 b, Vector3 c, Vector3 d) => new Quad3D(a, b, c, d);

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Vector3, Vector3, Vector3, Vector3)(Quad3D self) => (self.A, self.B, self.C, self.D);
        [MethodImpl(AggressiveInlining)] public static implicit operator Quad3D((Vector3, Vector3, Vector3, Vector3) value) => new(value.Item1, value.Item2, value.Item3, value.Item4);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Vector3 a, out Vector3 b, out Vector3 c, out Vector3 d) { a = A; b = B; c = C; d = D;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Quad3D other) => A.Equals(other.A) && B.Equals(other.B) && C.Equals(other.C) && D.Equals(other.D);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Quad3D other) => !A.Equals(other.A) && B.Equals(other.B) && C.Equals(other.C) && D.Equals(other.D);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Quad3D other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(A, B, C, D);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"A\" = {A}, \"B\" = {B}, \"C\" = {C}, \"D\" = {D} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        public Quad3D Flip { [MethodImpl(AggressiveInlining)] get  => (this.D, this.C, this.B, this.A); } 
public Vector3 Center { [MethodImpl(AggressiveInlining)] get  => this.A.Add(this.B.Add(this.C.Add(this.D))).Divide(((Number)4)); } 
public Line3D LineA { [MethodImpl(AggressiveInlining)] get  => (this.A, this.B); } 
public Line3D LineB { [MethodImpl(AggressiveInlining)] get  => (this.B, this.C); } 
public Line3D LineC { [MethodImpl(AggressiveInlining)] get  => (this.C, this.D); } 
public Line3D LineD { [MethodImpl(AggressiveInlining)] get  => (this.D, this.A); } 
public Triangle3D TriangleA { [MethodImpl(AggressiveInlining)] get  => (this.A, this.B, this.C); } 
public Triangle3D TriangleB { [MethodImpl(AggressiveInlining)] get  => (this.C, this.D, this.A); } 
public LineArray3D LineArray3D { [MethodImpl(AggressiveInlining)] get  => new LineArray3D(this.Lines); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator LineArray3D(Quad3D q) => q.LineArray3D;
        public TriangleArray3D TriangleArray3D { [MethodImpl(AggressiveInlining)] get  => new TriangleArray3D(this.Triangles); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator TriangleArray3D(Quad3D q) => q.TriangleArray3D;
        public QuadArray3D QuadArray3D { [MethodImpl(AggressiveInlining)] get  => new QuadArray3D(Intrinsics.MakeArray(this)); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator QuadArray3D(Quad3D q) => q.QuadArray3D;
        public TriangleMesh3D TriangleMesh3D { [MethodImpl(AggressiveInlining)] get  => this.TriangleArray3D; } 
[MethodImpl(AggressiveInlining)]  public static implicit operator TriangleMesh3D(Quad3D g) => g.TriangleMesh3D;
        public _T0 Points<_T0> where _T0 : IArray<_T0> { [MethodImpl(AggressiveInlining)] get  => Intrinsics.MakeArray(this.A, this.B, this.C, this.D); } 
public _T0 Lines<_T0> where _T0 : IArray<_T0> { [MethodImpl(AggressiveInlining)] get  => Intrinsics.MakeArray(new Line3D(this.A, this.B), new Line3D(this.B, this.C), new Line3D(this.C, this.D), new Line3D(this.D, this.A)); } 
public _T0 Triangles<_T0> where _T0 : IArray<_T0> { [MethodImpl(AggressiveInlining)] get  => Intrinsics.MakeArray(new Triangle3D(this.A, this.B, this.C), new Triangle3D(this.C, this.D, this.A)); } 
[MethodImpl(AggressiveInlining)]  public Quad3D Deform(System.Func<Vector3, Vector3> f) => (f.Invoke(this.A), f.Invoke(this.B), f.Invoke(this.C), f.Invoke(this.D));
[MethodImpl(AggressiveInlining)]  public _T0 Sample<_T0>(Integer numPoints) where _T0 : IArray<_T0>{
            var _var140 = this;
            return numPoints.LinearSpace.Map((x)  => _var140.Eval(x));
        }

[MethodImpl(AggressiveInlining)]  public PolyLine3D ToPolyLine3D(Integer numPoints) => (this.Sample(numPoints), this.Closed);
public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => ((Boolean)true); } 
[MethodImpl(AggressiveInlining)]  public Quad3D Deform<_T0>(_T0 t) where _T0 : ITransform3D{
            var _var141 = t;
            return this.Deform((v)  => _var141.Transform(v));
        }

[MethodImpl(AggressiveInlining)]  public Quad3D Translate(Vector3 v){
            var _var142 = v;
            return this.Deform((p)  => p.Add(_var142));
        }

[MethodImpl(AggressiveInlining)]  public Quad3D Rotate(Quaternion q){
            var _var143 = q;
            return this.Deform((v)  => _var143.Transform(v));
        }

[MethodImpl(AggressiveInlining)]  public Quad3D Scale(Vector3 v){
            var _var144 = v;
            return this.Deform((p)  => p.Multiply(_var144));
        }

[MethodImpl(AggressiveInlining)]  public Quad3D Scale(Number s){
            var _var145 = s;
            return this.Deform((p)  => p.Multiply(_var145));
        }

[MethodImpl(AggressiveInlining)]  public Quad3D RotateX(Angle a) => this.Rotate(a.RotateX);
[MethodImpl(AggressiveInlining)]  public Quad3D RotateY(Angle a) => this.Rotate(a.RotateY);
[MethodImpl(AggressiveInlining)]  public Quad3D RotateZ(Angle a) => this.Rotate(a.RotateZ);
[MethodImpl(AggressiveInlining)]  public Quad3D TranslateX(Number s){
            var _var146 = s;
            return this.Deform((p)  => p.Add((_var146, ((Integer)0), ((Integer)0))));
        }

[MethodImpl(AggressiveInlining)]  public Quad3D TranslateY(Number s){
            var _var147 = s;
            return this.Deform((p)  => p.Add((((Integer)0), _var147, ((Integer)0))));
        }

[MethodImpl(AggressiveInlining)]  public Quad3D TranslateZ(Number s){
            var _var148 = s;
            return this.Deform((p)  => p.Add((((Integer)0), ((Integer)0), _var148)));
        }

[MethodImpl(AggressiveInlining)]  public Quad3D ScaleX(Number s){
            var _var149 = s;
            return this.Deform((p)  => p.Multiply((_var149, ((Integer)1), ((Integer)1))));
        }

[MethodImpl(AggressiveInlining)]  public Quad3D ScaleY(Number s){
            var _var150 = s;
            return this.Deform((p)  => p.Multiply((((Integer)1), _var150, ((Integer)1))));
        }

[MethodImpl(AggressiveInlining)]  public Quad3D ScaleZ(Number s){
            var _var151 = s;
            return this.Deform((p)  => p.Multiply((((Integer)1), ((Integer)1), _var151)));
        }


        // Unimplemented concept functions
        public Integer PrimitiveSize => throw new NotImplementedException();
public Integer NumPrimitives => throw new NotImplementedException();
public _T0 Corners<_T0> where _T0 : IArray<_T0> => throw new NotImplementedException();
[MethodImpl(AggressiveInlining)]  public Vector3 Eval(Number t) => throw new NotImplementedException();
}
}
