// Autogenerated file: DO NOT EDIT
// Created on 2025-04-03 1:53:19 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Rect2D: IPolygon2D
    {
        // Fields
        [DataMember] public readonly Vector2 Center;
        [DataMember] public readonly Vector2 Size;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Rect2D WithCenter(Vector2 center) => new Rect2D(center, Size);
        [MethodImpl(AggressiveInlining)] public Rect2D WithSize(Vector2 size) => new Rect2D(Center, size);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Rect2D(Vector2 center, Vector2 size) { Center = center; Size = size; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Rect2D Create(Vector2 center, Vector2 size) => new Rect2D(center, size);

        // Static default implementation
        public static readonly Rect2D Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Vector2, Vector2)(Rect2D self) => (self.Center, self.Size);
        [MethodImpl(AggressiveInlining)] public static implicit operator Rect2D((Vector2, Vector2) value) => new(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Vector2 center, out Vector2 size) { center = Center; size = Size;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Rect2D other) => Center.Equals(other.Center) && Size.Equals(other.Size);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Rect2D other) => !Center.Equals(other.Center) && Size.Equals(other.Size);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Rect2D other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Center, Size);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Center\" = {Center}, \"Size\" = {Size} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        public Number Width { [MethodImpl(AggressiveInlining)] get  => this.Size.X; } 
public Number Height { [MethodImpl(AggressiveInlining)] get  => this.Size.Y; } 
public Number Left { [MethodImpl(AggressiveInlining)] get  => this.Center.X.Subtract(this.Width.Half); } 
public Number Right { [MethodImpl(AggressiveInlining)] get  => this.Left.Add(this.Width); } 
public Number Bottom { [MethodImpl(AggressiveInlining)] get  => this.Center.Y.Subtract(this.Height.Half); } 
public Number Top { [MethodImpl(AggressiveInlining)] get  => this.Bottom.Add(this.Height); } 
public Vector2 BottomLeft { [MethodImpl(AggressiveInlining)] get  => (this.Left, this.Bottom); } 
public Vector2 BottomRight { [MethodImpl(AggressiveInlining)] get  => (this.Right, this.Bottom); } 
public Vector2 TopRight { [MethodImpl(AggressiveInlining)] get  => (this.Right, this.Top); } 
public Vector2 TopLeft { [MethodImpl(AggressiveInlining)] get  => (this.Left, this.Top); } 
public Quad2D Quad2D { [MethodImpl(AggressiveInlining)] get  => (this.BottomLeft, this.BottomRight, this.TopRight, this.TopLeft); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Quad2D(Rect2D x) => x.Quad2D;
        // AMBIGUOUS FUNCTIONS 2
        public IArray<Vector2> Points { [MethodImpl(AggressiveInlining)] get  => this.Quad2D.Points; } 
public IArray<Line2D> Lines { [MethodImpl(AggressiveInlining)] get  => this.Points.WithNext((a, b)  => new Line2D(a, b), this.Closed); } 
[MethodImpl(AggressiveInlining)]  public IArray<Vector2> Sample(Integer numPoints){
            var _var89 = this;
            return numPoints.LinearSpace.Map((x)  => _var89.Eval(x));
        }

[MethodImpl(AggressiveInlining)]  public PolyLine2D ToPolyLine2D(Integer numPoints) => (this.Sample(numPoints), this.Closed);
public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => ((Boolean)true); } 

        // Unimplemented interface functions
        public Integer PrimitiveSize => throw new NotImplementedException();
public Integer NumPrimitives => throw new NotImplementedException();
public IArray<Vector2> Corners => throw new NotImplementedException();
[MethodImpl(AggressiveInlining)]  public Vector2 Eval(Number t) => throw new NotImplementedException();
}
}
