// Autogenerated file: DO NOT EDIT
// Created on 2025-04-08 12:25:04 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Rect2D: IPolygon2D<Rect2D>
    {
        // Fields
        [DataMember] public readonly Point2D Center;
        [DataMember] public readonly Vector2 Size;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Rect2D WithCenter(Point2D center) => new Rect2D(center, Size);
        [MethodImpl(AggressiveInlining)] public Rect2D WithSize(Vector2 size) => new Rect2D(Center, size);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Rect2D(Point2D center, Vector2 size) { Center = center; Size = size; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Rect2D Create(Point2D center, Vector2 size) => new Rect2D(center, size);

        // Static default implementation
        public static readonly Rect2D Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Point2D, Vector2)(Rect2D self) => (self.Center, self.Size);
        [MethodImpl(AggressiveInlining)] public static implicit operator Rect2D((Point2D, Vector2) value) => new Rect2D(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Point2D center, out Vector2 size) { center = Center; size = Size;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Rect2D other) => Center.Equals(other.Center) && Size.Equals(other.Size);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Rect2D other) => !Center.Equals(other.Center) && Size.Equals(other.Size);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Rect2D other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Center, Size);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Center\" = {Center}, \"Size\" = {Size} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        public Number Width { [MethodImpl(AggressiveInlining)] get  => this.Size.X; } 
public Number Height { [MethodImpl(AggressiveInlining)] get  => this.Size.Y; } 
public Number Left { [MethodImpl(AggressiveInlining)] get  => this.Center.X.Subtract(this.Width.Half); } 
public Number Right { [MethodImpl(AggressiveInlining)] get  => this.Left.Add(this.Width); } 
public Number Bottom { [MethodImpl(AggressiveInlining)] get  => this.Center.Y.Subtract(this.Height.Half); } 
public Number Top { [MethodImpl(AggressiveInlining)] get  => this.Bottom.Add(this.Height); } 
public Point2D BottomLeft { [MethodImpl(AggressiveInlining)] get  => (this.Left, this.Bottom); } 
public Point2D BottomRight { [MethodImpl(AggressiveInlining)] get  => (this.Right, this.Bottom); } 
public Point2D TopRight { [MethodImpl(AggressiveInlining)] get  => (this.Right, this.Top); } 
public Point2D TopLeft { [MethodImpl(AggressiveInlining)] get  => (this.Left, this.Top); } 
public Quad2D Quad2D { [MethodImpl(AggressiveInlining)] get  => (this.BottomLeft, this.BottomRight, this.TopRight, this.TopLeft); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Quad2D(Rect2D x) => x.Quad2D;
        public IArray<Point2D> Points { [MethodImpl(AggressiveInlining)] get  => this.Quad2D.Points; } 
public IArray<Line2D> Lines { [MethodImpl(AggressiveInlining)] get  => this.Points.WithNext((a, b)  => new Line2D(a, b), this.Closed); } 
[MethodImpl(AggressiveInlining)]  public Point2D Point(Integer index) => this.Points.At(index);
[MethodImpl(AggressiveInlining)]  public Triangle2D Triangle(Integer3 f) => (this.Point(f.A), this.Point(f.B), this.Point(f.C));
[MethodImpl(AggressiveInlining)]  public Quad2D Quad(Integer4 f) => (this.Point(f.A), this.Point(f.B), this.Point(f.C), this.Point(f.D));
public Bounds2D Bounds { [MethodImpl(AggressiveInlining)] get  => this.Points.Bounds(); } 
[MethodImpl(AggressiveInlining)]  public IArray<Point2D> Sample(Integer numPoints){
            var _var98 = this;
            return numPoints.LinearSpace.Map((x)  => _var98.Eval(x));
        }

[MethodImpl(AggressiveInlining)]  public PolyLine2D ToPolyLine2D(Integer numPoints) => (this.Sample(numPoints), this.Closed);
public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => ((Boolean)true); } 

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)]  public Rect2D Deform(System.Func<Point2D, Point2D> f) => throw new NotImplementedException();
[MethodImpl(AggressiveInlining)]  public Point2D Eval(Number t) => throw new NotImplementedException();
}
}
