// Autogenerated file: DO NOT EDIT
// Created on 2025-04-08 12:25:04 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Scaling3D: ITransform3D
    {
        // Fields
        [DataMember] public readonly Vector3 Amount;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Scaling3D WithAmount(Vector3 amount) => new Scaling3D(amount);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Scaling3D(Vector3 amount) { Amount = amount; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Scaling3D Create(Vector3 amount) => new Scaling3D(amount);

        // Static default implementation
        public static readonly Scaling3D Default = default;

        // Implicit converters to/from single field
        [MethodImpl(AggressiveInlining)] public static implicit operator Vector3(Scaling3D self) => self.Amount;
        [MethodImpl(AggressiveInlining)] public static implicit operator Scaling3D(Vector3 value) => new Scaling3D(value);

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Scaling3D other) => Amount.Equals(other.Amount);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Scaling3D other) => !Amount.Equals(other.Amount);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Scaling3D other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Amount);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Amount\" = {Amount} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        public Matrix4x4 Matrix { [MethodImpl(AggressiveInlining)] get  => Matrix4x4.CreateScale(this.Amount.X, this.Amount.Y, this.Amount.Z); } 
public static Scaling3D Identity { [MethodImpl(AggressiveInlining)] get  => Vector3.One; } 
[MethodImpl(AggressiveInlining)]  public Point3D Multiply(Point3D v) => this.TransformPoint(v);
[MethodImpl(AggressiveInlining)]  public static Point3D operator *(Scaling3D x, Point3D v) => x.Multiply(v);
        [MethodImpl(AggressiveInlining)]  public Vector3 Multiply(Vector3 v) => this.TransformNormal(v);
[MethodImpl(AggressiveInlining)]  public static Vector3 operator *(Scaling3D x, Vector3 v) => x.Multiply(v);
        [MethodImpl(AggressiveInlining)]  public MatrixTransform3D Multiply(Matrix4x4 m) => this.Compose(m);
[MethodImpl(AggressiveInlining)]  public static MatrixTransform3D operator *(Scaling3D x, Matrix4x4 m) => x.Multiply(m);
        [MethodImpl(AggressiveInlining)]  public Point3D TransformPoint(Point3D v) => v.Vector3.Transform(this.Matrix);
[MethodImpl(AggressiveInlining)]  public Vector3 TransformNormal(Vector3 v) => v.TransformNormal(this.Matrix);
public Matrix4x4 Matrix4x4 { [MethodImpl(AggressiveInlining)] get  => this.Matrix; } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Matrix4x4(Scaling3D t) => t.Matrix4x4;
        public MatrixTransform3D Invert { [MethodImpl(AggressiveInlining)] get  => this.Matrix.Invert; } 
[MethodImpl(AggressiveInlining)]  public MatrixTransform3D Compose(Matrix4x4 m) => this.Matrix.Multiply(m);
public Rotation3D Rotation { [MethodImpl(AggressiveInlining)] get  => this.Matrix.Rotation; } 
public Translation3D Translation { [MethodImpl(AggressiveInlining)] get  => this.Matrix.Translation; } 
public Pose3D Pose { [MethodImpl(AggressiveInlining)] get  => (this.Matrix.Translation, this.Matrix.Rotation); } 

        // Unimplemented interface functions
    }
}
