// Autogenerated file: DO NOT EDIT
// Created on 2025-04-08 12:25:04 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct String: IValue, IOrderable<String>
    {
        // Static factory function
        [MethodImpl(AggressiveInlining)] public static String Create() => new String();

        // Static default implementation
        public static readonly String Default = default;

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(String other) => Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(String other) => !Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is String other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public static Boolean operator==(String a, String b) => a.Equals(b);
        [MethodImpl(AggressiveInlining)] public static Boolean operator!=(String a, String b) => !a.Equals(b);
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Value.GetHashCode();
        [MethodImpl(AggressiveInlining)] public override string ToString() => Value.ToString();

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)]  public Boolean LessThan(String b) => this.LessThanOrEquals(b).And(this.NotEquals(b));
[MethodImpl(AggressiveInlining)]  public Boolean GreaterThan(String b) => b.LessThan(this);
[MethodImpl(AggressiveInlining)]  public Boolean GreaterThanOrEquals(String b) => b.LessThanOrEquals(this);
[MethodImpl(AggressiveInlining)]  public String Lesser(String b) => this.LessThanOrEquals(b) ? this : b;
[MethodImpl(AggressiveInlining)]  public String Greater(String b) => this.GreaterThanOrEquals(b) ? this : b;
[MethodImpl(AggressiveInlining)]  public Integer CompareTo(String b) => this.LessThanOrEquals(b) ? this.Equals(b) ? ((Integer)0) : ((Integer)1).Negative : ((Integer)1);

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)]  public Boolean LessThanOrEquals(String y) => this <= y;
    }
}
