// Autogenerated file: DO NOT EDIT
// Created on 2025-04-08 12:25:04 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct TrefoilKnot: IAngularCurve3D, IClosedShape
    {
        // Fields

        // With functions 

        // Regular Constructor

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static TrefoilKnot Create() => new TrefoilKnot();

        // Static default implementation
        public static readonly TrefoilKnot Default = default;

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is TrefoilKnot;
        [MethodImpl(AggressiveInlining)] public Boolean Equals(TrefoilKnot other) => true;
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(TrefoilKnot other) => false;
        [MethodImpl(AggressiveInlining)] public static Boolean operator==(TrefoilKnot a, TrefoilKnot b) => true;
        [MethodImpl(AggressiveInlining)] public static Boolean operator!=(TrefoilKnot a, TrefoilKnot b) => false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes();
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{  }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)]  public Point3D Eval(Angle t) => t.TrefoilKnot;
[MethodImpl(AggressiveInlining)]  public Point3D Eval(Number t) => this.Eval(t.Turns);
[MethodImpl(AggressiveInlining)]  public IArray<Point3D> Sample(Integer numPoints){
            var _var85 = this;
            return numPoints.LinearSpace.Map((x)  => _var85.Eval(x));
        }

[MethodImpl(AggressiveInlining)]  public PolyLine3D ToPolyLine3D(Integer numPoints) => (this.Sample(numPoints), this.Closed);
public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => ((Boolean)true); } 

        // Unimplemented interface functions
    }
}
