// Autogenerated file: DO NOT EDIT
// Created on 2025-04-03 1:53:19 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Vector2: INumerical<Vector2>
    {
        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Vector2 Create(Number x, Number y) => new Vector2(x, y);

        // Static default implementation
        public static readonly Vector2 Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number)(Vector2 self) => (self.X, self.Y);
        [MethodImpl(AggressiveInlining)] public static implicit operator Vector2((Number, Number) value) => new(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number x, out Number y) { x = X; y = Y;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Vector2 other) => Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Vector2 other) => !Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Vector2 other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public static Boolean operator==(Vector2 a, Vector2 b) => a.Equals(b);
        [MethodImpl(AggressiveInlining)] public static Boolean operator!=(Vector2 a, Vector2 b) => !a.Equals(b);
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Value.GetHashCode();
        [MethodImpl(AggressiveInlining)] public override string ToString() => Value.ToString();

        // Explicit implementation of interfaces by forwarding properties to fields

        // IArrayLike predefined functions
        public Integer NumComponents { [MethodImpl(AggressiveInlining)] get => 2; }
        public IArray<Number> Components { [MethodImpl(AggressiveInlining)] get => Intrinsics.MakeArray<Number>(X, Y); }
        [MethodImpl(AggressiveInlining)] public static Vector2 CreateFromComponents(IArray<Number> numbers) => new Vector2(numbers[0], numbers[1]);

        [MethodImpl(AggressiveInlining)] public static Vector2 CreateFromComponent(Number x) => new Vector2(x, x);

        // Implemented interface functions
        public Vector3 To3D { [MethodImpl(AggressiveInlining)] get  => (this.X, this.Y, ((Integer)0)); } 
[MethodImpl(AggressiveInlining)]  public Vector2 Add(Vector2 right) => this + right;
        [MethodImpl(AggressiveInlining)]  public Vector2 Subtract(Vector2 right) => this - right;
        [MethodImpl(AggressiveInlining)]  public Vector2 Multiply(Vector2 right) => this * right;
        [MethodImpl(AggressiveInlining)]  public Vector2 Multiply(Number scalar) => this * scalar;
        [MethodImpl(AggressiveInlining)]  public Vector2 Divide(Vector2 right) => this / right;
        [MethodImpl(AggressiveInlining)]  public Vector2 Divide(Number scalar) => this / scalar;
        public Vector2 Negative { [MethodImpl(AggressiveInlining)] get => -this; }
        [MethodImpl(AggressiveInlining)]  public Line2D Line(Vector2 b) => (this, b);
[MethodImpl(AggressiveInlining)]  public Ray2D Ray(Vector2 b) => (this, b);
[MethodImpl(AggressiveInlining)]  public Ray2D RayTo(Vector2 b) => (this, b.Subtract(this));
[MethodImpl(AggressiveInlining)]  public Vector3 Vector3(Number z) => (this.X, this.Y, z);
public static Vector2 UnitX { [MethodImpl(AggressiveInlining)] get  => (((Number)1), ((Number)0)); } 
public static Vector2 UnitY { [MethodImpl(AggressiveInlining)] get  => (((Number)0), ((Number)1)); } 
// AMBIGUOUS FUNCTIONS 2
        [MethodImpl(AggressiveInlining)]  public Vector2 Lerp(Vector2 b, Number t) => this.Multiply(t.FromOne).Add(b.Multiply(t));
[MethodImpl(AggressiveInlining)]  public Vector2 Barycentric(Vector2 v2, Vector2 v3, Vector2 uv) => this.Add(v2.Subtract(this)).Multiply(uv.X).Add(v3.Subtract(this).Multiply(uv.Y));
[MethodImpl(AggressiveInlining)]  public Vector2 Linear(Vector2 b, Number x) => this.Multiply(x).Add(b);
[MethodImpl(AggressiveInlining)]  public Vector2 Quadratic(Vector2 b, Vector2 c, Number x) => this.Multiply(x.Sqr).Add(b.Multiply(x).Add(c));
[MethodImpl(AggressiveInlining)]  public Vector2 Cubic(Vector2 b, Vector2 c, Vector2 d, Number x) => this.Multiply(x.Cube).Add(b.Multiply(x.Sqr).Add(c.Multiply(x).Add(d)));
[MethodImpl(AggressiveInlining)]  public Vector2 Quartic(Vector2 b, Vector2 c, Vector2 d, Vector2 e, Number x) => this.Multiply(x.Pow(((Integer)4))).Add(b.Multiply(x.Cube).Add(c.Multiply(x.Sqr).Add(d.Multiply(x).Add(e))));
[MethodImpl(AggressiveInlining)]  public Vector2 LinearDerivative(Vector2 b, Number x) => this;
[MethodImpl(AggressiveInlining)]  public Vector2 LinearSecondDerivative(Vector2 b, Number x) => default;
[MethodImpl(AggressiveInlining)]  public Vector2 QuadraticDerivative(Vector2 b, Vector2 c, Number x) => this.Multiply(((Number)2)).Multiply(x).Add(b);
[MethodImpl(AggressiveInlining)]  public Vector2 QuadraticSecondDerivative(Vector2 b, Vector2 c, Number x) => this.Multiply(((Number)2));
[MethodImpl(AggressiveInlining)]  public Vector2 CubicDerivative(Vector2 b, Vector2 c, Vector2 d, Number x) => this.Multiply(((Number)3)).Multiply(x.Sqr).Add(b.Multiply(((Number)2)).Multiply(x).Add(c));
[MethodImpl(AggressiveInlining)]  public Vector2 CubicSecondDerivative(Vector2 b, Vector2 c, Vector2 d, Number x) => this.Multiply(((Number)6)).Multiply(x).Add(b.Multiply(((Number)2)));
[MethodImpl(AggressiveInlining)]  public Vector2 QuarticSecondDerivative(Vector2 b, Vector2 c, Vector2 d, Vector2 e, Number x) => this.Multiply(((Number)12)).Multiply(x.Sqr).Add(b.Multiply(((Number)6)).Multiply(x).Add(c.Multiply(((Number)2))));
[MethodImpl(AggressiveInlining)]  public Vector2 CubicBezier(Vector2 b, Vector2 c, Vector2 d, Number t) => this.Multiply(((Number)1).Subtract(t).Cube).Add(b.Multiply(((Number)3).Multiply(((Number)1).Subtract(t).Sqr.Multiply(t))).Add(c.Multiply(((Number)3).Multiply(((Number)1).Subtract(t).Multiply(t.Sqr))).Add(d.Multiply(t.Cube))));
[MethodImpl(AggressiveInlining)]  public Vector2 CubicBezierDerivative(Vector2 b, Vector2 c, Vector2 d, Number t) => b.Subtract(this).Multiply(((Number)3).Multiply(((Number)1).Subtract(t).Sqr)).Add(c.Subtract(b).Multiply(((Number)6).Multiply(((Number)1).Subtract(t).Multiply(t))).Add(d.Subtract(c).Multiply(((Number)3).Multiply(t.Sqr))));
[MethodImpl(AggressiveInlining)]  public Vector2 CubicBezierSecondDerivative(Vector2 b, Vector2 c, Vector2 d, Number t) => c.Subtract(b.Multiply(((Number)2)).Add(this)).Multiply(((Number)6).Multiply(((Number)1).Subtract(t))).Add(d.Subtract(c.Multiply(((Number)2)).Add(b)).Multiply(((Number)6).Multiply(t)));
[MethodImpl(AggressiveInlining)]  public Vector2 QuadraticBezier(Vector2 b, Vector2 c, Number t) => this.Multiply(((Number)1).Subtract(t).Sqr).Add(b.Multiply(((Number)2).Multiply(((Number)1).Subtract(t).Multiply(t))).Add(c.Multiply(t.Sqr)));
[MethodImpl(AggressiveInlining)]  public Vector2 QuadraticBezierDerivative(Vector2 b, Vector2 c, Number t) => b.Subtract(this).Multiply(((Number)2).Multiply(((Number)1).Subtract(t))).Add(c.Subtract(b).Multiply(((Number)2).Multiply(t)));
[MethodImpl(AggressiveInlining)]  public Vector2 QuadraticBezierSecondDerivative(Vector2 b, Vector2 c, Number t) => ((Number)2).Multiply(this.Subtract(b.Multiply(((Number)2)).Add(c)));
[MethodImpl(AggressiveInlining)]  public Vector2 Hermite(Vector2 p1, Vector2 m0, Vector2 m1, Number t) => this.Multiply(((Number)2).Multiply(t.Cube).Subtract(((Number)3).Multiply(t.Sqr).Add(((Number)1)))).Add(m0.Multiply(t.Cube.Subtract(((Number)2).Multiply(t.Sqr).Add(t))).Add(p1.Multiply(((Number)2).Multiply(t.Cube).Add(((Number)3).Multiply(t.Sqr)).Negative).Add(m1.Multiply(t.Cube.Subtract(t.Sqr)))));
[MethodImpl(AggressiveInlining)]  public Vector2 HermiteDerivative(Vector2 p1, Vector2 m0, Vector2 m1, Number t) => this.Multiply(((Number)6).Multiply(t.Sqr).Subtract(((Number)6).Multiply(t))).Add(m0.Multiply(((Number)3).Multiply(t.Sqr).Subtract(((Number)4).Multiply(t).Add(((Number)1)))).Add(p1.Multiply(((Number)6).Multiply(t.Sqr).Add(((Number)6).Multiply(t)).Negative).Add(m1.Multiply(((Number)3).Multiply(t.Sqr).Subtract(((Number)2).Multiply(t))))));
[MethodImpl(AggressiveInlining)]  public Vector2 CatmullRom(Vector2 p1, Vector2 p2, Vector2 p3, Number t) => ((Number)0.5).Multiply(p1.Multiply(((Number)2)).Add(p2.Subtract(this).Multiply(t).Add(this.Multiply(((Number)2)).Subtract(p1.Multiply(((Number)5)).Add(p2.Multiply(((Number)4)).Subtract(p3))).Multiply(t.Sqr).Add(this.Add(p1.Multiply(((Number)3)).Subtract(p2.Multiply(((Number)3)).Add(p3))).Negative.Multiply(t.Cube)))));
[MethodImpl(AggressiveInlining)]  public Vector2 CatmullRomDerivative(Vector2 p1, Vector2 p2, Vector2 p3, Number t) => ((Number)0.5).Multiply(p2.Subtract(this).Add(((Number)2).Multiply(this.Multiply(((Number)2)).Subtract(p1.Multiply(((Number)5)).Add(p2.Multiply(((Number)4)).Subtract(p3))).Multiply(t)).Add(((Number)3).Multiply(this.Add(p1.Multiply(((Number)3)).Subtract(p2.Multiply(((Number)3)).Add(p3))).Negative.Multiply(t.Sqr)))));
public Vector2 SmoothStep { [MethodImpl(AggressiveInlining)] get  => this.Sqr.Multiply(this.Twice.Add(((Number)3)).Negative); } 
public Vector2 SmootherStep { [MethodImpl(AggressiveInlining)] get  => this.Cube.Multiply(this.Multiply(((Number)6)).Subtract(((Number)15))).Add(((Number)10)); } 
[MethodImpl(AggressiveInlining)]  public Vector2 MidPoint(Vector2 b) => this.Add(b).Half;
[MethodImpl(AggressiveInlining)]  public Number Reduce(Number initial, System.Func<Number, Number, Number> f) => this.Components.Reduce(initial, f);
public Number Sum { [MethodImpl(AggressiveInlining)] get  => this.Reduce(((Number)0), (a, b)  => a.Add(b)); } 
public Number SumSquares { [MethodImpl(AggressiveInlining)] get  => this.Sqr.Sum; } 
public Number MagnitudeSquared { [MethodImpl(AggressiveInlining)] get  => this.SumSquares; } 
public Number Magnitude { [MethodImpl(AggressiveInlining)] get  => this.MagnitudeSquared.Sqrt; } 
[MethodImpl(AggressiveInlining)]  public Vector2 Project(Vector2 other) => other.Multiply(this.Dot(other));
[MethodImpl(AggressiveInlining)]  public Angle Angle(Vector2 b) => this.Dot(b).Divide(this.Magnitude.Multiply(b.Magnitude)).Acos;
[MethodImpl(AggressiveInlining)]  public Boolean IsParallel(Vector2 b) => this.Dot(b).Abs.GreaterThanOrEquals(((Number)1).Subtract(Constants.Epsilon));
public static Vector2 Zero { [MethodImpl(AggressiveInlining)] get  => Vector2.CreateFromComponent(((Number)0)); } 
public static Vector2 One { [MethodImpl(AggressiveInlining)] get  => Vector2.CreateFromComponent(((Number)1)); } 
[MethodImpl(AggressiveInlining)]  public static Vector2 FromNumber(Number x) => Vector2.CreateFromComponent(x);
public Vector2 PlusOne { [MethodImpl(AggressiveInlining)] get  => this.Add(One); } 
public Vector2 MinusOne { [MethodImpl(AggressiveInlining)] get  => this.Subtract(One); } 
public Vector2 FromOne { [MethodImpl(AggressiveInlining)] get  => this.Add(One).Negative; } 
[MethodImpl(AggressiveInlining)]  public Number Component(Integer n) => this.Components.At(n);
public Number MaxComponent { [MethodImpl(AggressiveInlining)] get  => this.Reduce(this.Component(((Integer)0)), (a, b)  => a.Max(b)); } 
public Number MinComponent { [MethodImpl(AggressiveInlining)] get  => this.Reduce(this.Component(((Integer)0)), (a, b)  => a.Min(b)); } 
[MethodImpl(AggressiveInlining)]  public Vector2 MapComponents(System.Func<Number, Number> f) => Vector2.CreateFromComponents(this.Components.Map(f));
[MethodImpl(AggressiveInlining)]  public Vector2 ZipComponents(Vector2 b, System.Func<Number, Number, Number> f) => Vector2.CreateFromComponents(this.Components.Zip(b.Components, f));
[MethodImpl(AggressiveInlining)]  public Vector2 ZipComponents(Vector2 b, Vector2 c, System.Func<Number, Number, Number, Number> f) => Vector2.CreateFromComponents(this.Components.Zip(b.Components, c.Components, f));
[MethodImpl(AggressiveInlining)]  public Boolean AllZipComponents(Vector2 b, System.Func<Number, Number, Boolean> f) => this.Components.Zip(b.Components, f).All((x)  => x);
[MethodImpl(AggressiveInlining)]  public Boolean AllZipComponents(Vector2 b, Vector2 c, System.Func<Number, Number, Number, Boolean> f) => this.Components.Zip(b.Components, c.Components, f).All((x)  => x);
[MethodImpl(AggressiveInlining)]  public Boolean AnyZipComponents(Vector2 b, System.Func<Number, Number, Boolean> f) => this.Components.Zip(b.Components, f).Any((x)  => x);
[MethodImpl(AggressiveInlining)]  public Boolean AnyZipComponents(Vector2 b, Vector2 c, System.Func<Number, Number, Number, Boolean> f) => this.Components.Zip(b.Components, c.Components, f).Any((x)  => x);
[MethodImpl(AggressiveInlining)]  public Boolean AllComponents(System.Func<Number, Boolean> predicate) => this.Components.All(predicate);
[MethodImpl(AggressiveInlining)]  public Boolean AnyComponent(System.Func<Number, Boolean> predicate) => this.Components.Any(predicate);
[MethodImpl(AggressiveInlining)]  public Vector2 InversePow(Vector2 n) => this.Pow(n.Reciprocal);
public Vector2 Fract { [MethodImpl(AggressiveInlining)] get  => this.Subtract(this.Floor); } 
public Vector2 Pow2 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((a)  => a.Multiply(a)); } 
public Vector2 Pow3 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((a)  => a.Multiply(a.Multiply(a))); } 
public Vector2 Pow4 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((a)  => a.Multiply(a.Multiply(a.Multiply(a)))); } 
public Vector2 Pow5 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((a)  => a.Multiply(a.Multiply(a.Multiply(a.Multiply(a))))); } 
public Vector2 Sqr { [MethodImpl(AggressiveInlining)] get  => this.Pow2; } 
public Vector2 Cube { [MethodImpl(AggressiveInlining)] get  => this.Pow3; } 
public Vector2 ClampZeroOne { [MethodImpl(AggressiveInlining)] get  => this.Clamp(Zero, One); } 
[MethodImpl(AggressiveInlining)]  public Boolean Between(Vector2 a, Vector2 b) => this.AllZipComponents(a, b, (x0, a0, b0)  => x0.Between(a0, b0));
public Boolean BetweenZeroOne { [MethodImpl(AggressiveInlining)] get  => this.Between(Zero, One); } 
[MethodImpl(AggressiveInlining)]  public Vector2 Pow(Vector2 y) => this.ZipComponents(y, (a, b)  => a.Pow(b));
public Vector2 Reciprocal { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((n)  => n.Reciprocal); } 
public Vector2 Half { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)2)); } 
public Vector2 Quarter { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)4)); } 
public Vector2 Eight { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)8)); } 
public Vector2 Sixteenth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)16)); } 
public Vector2 Tenth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)10)); } 
public Vector2 Twice { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)2)); } 
public Vector2 Hundred { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)100)); } 
public Vector2 Thousand { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)1000)); } 
public Vector2 Million { [MethodImpl(AggressiveInlining)] get  => this.Thousand.Thousand; } 
public Vector2 Billion { [MethodImpl(AggressiveInlining)] get  => this.Thousand.Million; } 
public Vector2 Hundredth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)100)); } 
public Vector2 Thousandth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)1000)); } 
public Vector2 Millionth { [MethodImpl(AggressiveInlining)] get  => this.Thousandth.Thousandth; } 
public Vector2 Billionth { [MethodImpl(AggressiveInlining)] get  => this.Thousandth.Millionth; } 
[MethodImpl(AggressiveInlining)]  public Number At(Integer n) => this.Components.At(n);
public Number this[Integer n] { [MethodImpl(AggressiveInlining)]  get => At(n); }

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)]  public Vector2 Modulo(Vector2 b) => this % b;
        [MethodImpl(AggressiveInlining)]  public Vector2 Modulo(Number other) => this % other;
    }
}
