// Autogenerated file: DO NOT EDIT
// Created on 2025-04-08 12:25:04 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Vector8: IVector<Vector8>
    {
        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Vector8 Create(Number x0, Number x1, Number x2, Number x3, Number x4, Number x5, Number x6, Number x7) => new Vector8(x0, x1, x2, x3, x4, x5, x6, x7);

        // Static default implementation
        public static readonly Vector8 Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number, Number, Number, Number, Number, Number, Number)(Vector8 self) => (self.X0, self.X1, self.X2, self.X3, self.X4, self.X5, self.X6, self.X7);
        [MethodImpl(AggressiveInlining)] public static implicit operator Vector8((Number, Number, Number, Number, Number, Number, Number, Number) value) => new Vector8(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5, value.Item6, value.Item7, value.Item8);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number x0, out Number x1, out Number x2, out Number x3, out Number x4, out Number x5, out Number x6, out Number x7) { x0 = X0; x1 = X1; x2 = X2; x3 = X3; x4 = X4; x5 = X5; x6 = X6; x7 = X7;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Vector8 other) => Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Vector8 other) => !Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Vector8 other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public static Boolean operator==(Vector8 a, Vector8 b) => a.Equals(b);
        [MethodImpl(AggressiveInlining)] public static Boolean operator!=(Vector8 a, Vector8 b) => !a.Equals(b);
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Value.GetHashCode();
        [MethodImpl(AggressiveInlining)] public override string ToString() => Value.ToString();

        // Explicit implementation of interfaces by forwarding properties to fields

        // IArrayLike predefined functions
        public Integer NumComponents { [MethodImpl(AggressiveInlining)] get => 8; }
        public IArray<Number> Components { [MethodImpl(AggressiveInlining)] get => Intrinsics.MakeArray<Number>(X0, X1, X2, X3, X4, X5, X6, X7); }
        [MethodImpl(AggressiveInlining)] public static Vector8 CreateFromComponents(IArray<Number> numbers) => new Vector8(numbers[0], numbers[1], numbers[2], numbers[3], numbers[4], numbers[5], numbers[6], numbers[7]);

        [MethodImpl(AggressiveInlining)] public static Vector8 CreateFromComponent(Number x) => new Vector8(x, x, x, x, x, x, x, x);

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)]  public Vector8 Add(Vector8 right) => this + right;
        [MethodImpl(AggressiveInlining)]  public Vector8 Subtract(Vector8 right) => this - right;
        [MethodImpl(AggressiveInlining)]  public Vector8 Multiply(Vector8 right) => this * right;
        [MethodImpl(AggressiveInlining)]  public Vector8 Multiply(Number scalar) => this * scalar;
        [MethodImpl(AggressiveInlining)]  public Vector8 Divide(Vector8 right) => this / right;
        [MethodImpl(AggressiveInlining)]  public Vector8 Divide(Number scalar) => this / scalar;
        public Vector8 Negative { [MethodImpl(AggressiveInlining)] get => -this; }
        [MethodImpl(AggressiveInlining)]  public Vector8 BitwiseAnd(Vector8 b) => this & b;
        [MethodImpl(AggressiveInlining)]  public Vector8 BitwiseOr(Vector8 b) => this | b;
        public Vector8 Complement { [MethodImpl(AggressiveInlining)] get => ~this; }
        [MethodImpl(AggressiveInlining)]  public Vector8 LessThan(Vector8 b) => this < b;
        [MethodImpl(AggressiveInlining)]  public Vector8 LessThanOrEquals(Vector8 b) => this <= b;
        [MethodImpl(AggressiveInlining)]  public Vector8 GreaterThan(Vector8 b) => this > b;
        [MethodImpl(AggressiveInlining)]  public Vector8 GreaterThanOrEquals(Vector8 b) => this >= b;
        public Vector8 Normalize { [MethodImpl(AggressiveInlining)] get  => this.MagnitudeSquared.GreaterThan(((Integer)0)) ? this.Divide(this.Magnitude) : Zero; } 
[MethodImpl(AggressiveInlining)]  public Vector8 Reflect(Vector8 normal) => this.Subtract(normal.Multiply(this.Dot(normal).Multiply(((Number)2))));
[MethodImpl(AggressiveInlining)]  public Vector8 Project(Vector8 other) => other.Multiply(this.Dot(other));
[MethodImpl(AggressiveInlining)]  public Number Distance(Vector8 b) => b.Subtract(this).Magnitude;
[MethodImpl(AggressiveInlining)]  public Number DistanceSquared(Vector8 b) => b.Subtract(this).MagnitudeSquared;
[MethodImpl(AggressiveInlining)]  public Angle Angle(Vector8 b) => this.Dot(b).Divide(this.Magnitude.Multiply(b.Magnitude)).Acos;
[MethodImpl(AggressiveInlining)]  public Boolean IsParallel(Vector8 b) => this.Dot(b).Abs.GreaterThanOrEquals(((Number)1).Subtract(Constants.Epsilon));
public Vector8 PlusOne { [MethodImpl(AggressiveInlining)] get  => this.Add(One); } 
public Vector8 MinusOne { [MethodImpl(AggressiveInlining)] get  => this.Subtract(One); } 
// AMBIGUOUS FUNCTIONS 2
        public Vector8 FromOne { [MethodImpl(AggressiveInlining)] get  => this.Add(One).Negative; } 
public Number Length { [MethodImpl(AggressiveInlining)] get  => this.Magnitude; } 
public Number LengthSquared { [MethodImpl(AggressiveInlining)] get  => this.MagnitudeSquared; } 
[MethodImpl(AggressiveInlining)]  public Vector8 Barycentric(Vector8 v2, Vector8 v3, Vector2 uv) => this.Add(v2.Subtract(this)).Multiply(uv.X).Add(v3.Subtract(this).Multiply(uv.Y));
[MethodImpl(AggressiveInlining)]  public Vector8 Linear(Vector8 b, Number x) => this.Multiply(x).Add(b);
[MethodImpl(AggressiveInlining)]  public Vector8 Quadratic(Vector8 b, Vector8 c, Number x) => this.Multiply(x.Sqr).Add(b.Multiply(x).Add(c));
[MethodImpl(AggressiveInlining)]  public Vector8 Cubic(Vector8 b, Vector8 c, Vector8 d, Number x) => this.Multiply(x.Pow3).Add(b.Multiply(x.Sqr).Add(c.Multiply(x).Add(d)));
[MethodImpl(AggressiveInlining)]  public Vector8 Quartic(Vector8 b, Vector8 c, Vector8 d, Vector8 e, Number x) => this.Multiply(x.Pow(((Integer)4))).Add(b.Multiply(x.Pow3).Add(c.Multiply(x.Sqr).Add(d.Multiply(x).Add(e))));
[MethodImpl(AggressiveInlining)]  public Vector8 LinearDerivative(Vector8 b, Number x) => this;
[MethodImpl(AggressiveInlining)]  public Vector8 LinearSecondDerivative(Vector8 b, Number x) => default;
[MethodImpl(AggressiveInlining)]  public Vector8 QuadraticDerivative(Vector8 b, Vector8 c, Number x) => this.Multiply(((Number)2)).Multiply(x).Add(b);
[MethodImpl(AggressiveInlining)]  public Vector8 QuadraticSecondDerivative(Vector8 b, Vector8 c, Number x) => this.Multiply(((Number)2));
[MethodImpl(AggressiveInlining)]  public Vector8 CubicDerivative(Vector8 b, Vector8 c, Vector8 d, Number x) => this.Multiply(((Number)3)).Multiply(x.Sqr).Add(b.Multiply(((Number)2)).Multiply(x).Add(c));
[MethodImpl(AggressiveInlining)]  public Vector8 CubicSecondDerivative(Vector8 b, Vector8 c, Vector8 d, Number x) => this.Multiply(((Number)6)).Multiply(x).Add(b.Multiply(((Number)2)));
[MethodImpl(AggressiveInlining)]  public Vector8 QuarticSecondDerivative(Vector8 b, Vector8 c, Vector8 d, Vector8 e, Number x) => this.Multiply(((Number)12)).Multiply(x.Sqr).Add(b.Multiply(((Number)6)).Multiply(x).Add(c.Multiply(((Number)2))));
[MethodImpl(AggressiveInlining)]  public Vector8 CubicBezier(Vector8 b, Vector8 c, Vector8 d, Number t) => this.Multiply(((Number)1).Subtract(t).Pow3).Add(b.Multiply(((Number)3).Multiply(((Number)1).Subtract(t).Sqr.Multiply(t))).Add(c.Multiply(((Number)3).Multiply(((Number)1).Subtract(t).Multiply(t.Sqr))).Add(d.Multiply(t.Pow3))));
[MethodImpl(AggressiveInlining)]  public Vector8 CubicBezierDerivative(Vector8 b, Vector8 c, Vector8 d, Number t) => b.Subtract(this).Multiply(((Number)3).Multiply(((Number)1).Subtract(t).Sqr)).Add(c.Subtract(b).Multiply(((Number)6).Multiply(((Number)1).Subtract(t).Multiply(t))).Add(d.Subtract(c).Multiply(((Number)3).Multiply(t.Sqr))));
[MethodImpl(AggressiveInlining)]  public Vector8 CubicBezierSecondDerivative(Vector8 b, Vector8 c, Vector8 d, Number t) => c.Subtract(b.Multiply(((Number)2)).Add(this)).Multiply(((Number)6).Multiply(((Number)1).Subtract(t))).Add(d.Subtract(c.Multiply(((Number)2)).Add(b)).Multiply(((Number)6).Multiply(t)));
[MethodImpl(AggressiveInlining)]  public Vector8 QuadraticBezier(Vector8 b, Vector8 c, Number t) => this.Multiply(((Number)1).Subtract(t).Sqr).Add(b.Multiply(((Number)2).Multiply(((Number)1).Subtract(t).Multiply(t))).Add(c.Multiply(t.Sqr)));
[MethodImpl(AggressiveInlining)]  public Vector8 QuadraticBezierDerivative(Vector8 b, Vector8 c, Number t) => b.Subtract(this).Multiply(((Number)2).Multiply(((Number)1).Subtract(t))).Add(c.Subtract(b).Multiply(((Number)2).Multiply(t)));
[MethodImpl(AggressiveInlining)]  public Vector8 QuadraticBezierSecondDerivative(Vector8 b, Vector8 c, Number t) => ((Number)2).Multiply(this.Subtract(b.Multiply(((Number)2)).Add(c)));
[MethodImpl(AggressiveInlining)]  public Vector8 Hermite(Vector8 p1, Vector8 m0, Vector8 m1, Number t) => this.Multiply(((Number)2).Multiply(t.Pow3).Subtract(((Number)3).Multiply(t.Sqr).Add(((Number)1)))).Add(m0.Multiply(t.Pow3.Subtract(((Number)2).Multiply(t.Sqr).Add(t))).Add(p1.Multiply(((Number)2).Multiply(t.Pow3).Add(((Number)3).Multiply(t.Sqr)).Negative).Add(m1.Multiply(t.Pow3.Subtract(t.Sqr)))));
[MethodImpl(AggressiveInlining)]  public Vector8 HermiteDerivative(Vector8 p1, Vector8 m0, Vector8 m1, Number t) => this.Multiply(((Number)6).Multiply(t.Sqr).Subtract(((Number)6).Multiply(t))).Add(m0.Multiply(((Number)3).Multiply(t.Sqr).Subtract(((Number)4).Multiply(t).Add(((Number)1)))).Add(p1.Multiply(((Number)6).Multiply(t.Sqr).Add(((Number)6).Multiply(t)).Negative).Add(m1.Multiply(((Number)3).Multiply(t.Sqr).Subtract(((Number)2).Multiply(t))))));
[MethodImpl(AggressiveInlining)]  public Vector8 CatmullRom(Vector8 p1, Vector8 p2, Vector8 p3, Number t) => ((Number)0.5).Multiply(p1.Multiply(((Number)2)).Add(p2.Subtract(this).Multiply(t).Add(this.Multiply(((Number)2)).Subtract(p1.Multiply(((Number)5)).Add(p2.Multiply(((Number)4)).Subtract(p3))).Multiply(t.Sqr).Add(this.Add(p1.Multiply(((Number)3)).Subtract(p2.Multiply(((Number)3)).Add(p3))).Negative.Multiply(t.Pow3)))));
[MethodImpl(AggressiveInlining)]  public Vector8 CatmullRomDerivative(Vector8 p1, Vector8 p2, Vector8 p3, Number t) => ((Number)0.5).Multiply(p2.Subtract(this).Add(((Number)2).Multiply(this.Multiply(((Number)2)).Subtract(p1.Multiply(((Number)5)).Add(p2.Multiply(((Number)4)).Subtract(p3))).Multiply(t)).Add(((Number)3).Multiply(this.Add(p1.Multiply(((Number)3)).Subtract(p2.Multiply(((Number)3)).Add(p3))).Negative.Multiply(t.Sqr)))));
public Vector8 SmoothStep { [MethodImpl(AggressiveInlining)] get  => this.Sqr.Multiply(this.Twice.Add(((Number)3)).Negative); } 
public Vector8 SmootherStep { [MethodImpl(AggressiveInlining)] get  => this.Pow3.Multiply(this.Multiply(((Number)6)).Subtract(((Number)15))).Add(((Number)10)); } 
public static Vector8 Zero { [MethodImpl(AggressiveInlining)] get  => Vector8.CreateFromComponent(((Number)0)); } 
public static Vector8 One { [MethodImpl(AggressiveInlining)] get  => Vector8.CreateFromComponent(((Number)1)); } 
public static Vector8 MinValue { [MethodImpl(AggressiveInlining)] get  => Vector8.CreateFromComponent(Number.MinValue); } 
public static Vector8 MaxValue { [MethodImpl(AggressiveInlining)] get  => Vector8.CreateFromComponent(Number.MaxValue); } 
[MethodImpl(AggressiveInlining)]  public Number Reduce(Number initial, System.Func<Number, Number, Number> f) => this.Components.Reduce(initial, f);
public Number MinComponent { [MethodImpl(AggressiveInlining)] get  => this.Reduce(this.At(((Integer)0)), (a, b)  => a.Min(b)); } 
public Number MaxComponent { [MethodImpl(AggressiveInlining)] get  => this.Reduce(this.At(((Integer)0)), (a, b)  => a.Max(b)); } 
public Number SumComponents { [MethodImpl(AggressiveInlining)] get  => this.Reduce(((Number)0), (a, b)  => a.Add(b)); } 
public Number SumSqrComponents { [MethodImpl(AggressiveInlining)] get  => this.Reduce(((Number)0), (a, b)  => a.Add(b.Multiply(b))); } 
public Number AvgComponent { [MethodImpl(AggressiveInlining)] get  => this.SumComponents.Divide(this.NumComponents); } 
public Number Magnitude { [MethodImpl(AggressiveInlining)] get  => this.MagnitudeSquared.Sqrt; } 
public Number MagnitudeSquared { [MethodImpl(AggressiveInlining)] get  => this.SumSqrComponents.Divide(this.NumComponents); } 
public Vector8 BitDecrement { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.BitDecrement); } 
public Vector8 BitIncrement { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.BitIncrement); } 
public Vector8 Cbrt { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Cbrt); } 
[MethodImpl(AggressiveInlining)]  public Vector8 FusedMultiplyAdd(Vector8 y, Vector8 z) => this.ZipComponents(y, z, (a, b, c)  => a.FusedMultiplyAdd(b, c));
public Vector8 ILogB { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ILogB); } 
[MethodImpl(AggressiveInlining)]  public Vector8 IEEERemainder(Vector8 y) => this.ZipComponents(y, (a, b)  => a.IEEERemainder(b));
public Vector8 Log10 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Log10); } 
[MethodImpl(AggressiveInlining)]  public Vector8 MinMagnitude(Vector8 other) => this.ZipComponents(other, (a, b)  => a.MinMagnitude(b));
[MethodImpl(AggressiveInlining)]  public Vector8 MaxMagnitude(Vector8 other) => this.ZipComponents(other, (a, b)  => a.MaxMagnitude(b));
public Vector8 NaturalLog { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.NaturalLog); } 
[MethodImpl(AggressiveInlining)]  public Vector8 Pow(Vector8 power) => this.ZipComponents(power, (a, b)  => a.Pow(b));
public Vector8 ReciprocalEstimate { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ReciprocalEstimate); } 
public Vector8 ReciprocalSquareRootEstimate { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ReciprocalSquareRootEstimate); } 
[MethodImpl(AggressiveInlining)]  public Vector8 RoundToZero(Integer digits){
            var _var209 = digits;
            return this.MapComponents((x)  => x.RoundToZero(_var209));
        }

[MethodImpl(AggressiveInlining)]  public Vector8 ScaleB(Integer n){
            var _var210 = n;
            return this.MapComponents((x)  => x.ScaleB(_var210));
        }

public Vector8 Square { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Sqr); } 
[MethodImpl(AggressiveInlining)]  public Boolean AlmostEqual(Vector8 y) => this.AllZipComponents(y, (a, b)  => a.AlmostEqual(b));
public Boolean AlmostZero { [MethodImpl(AggressiveInlining)] get  => this.AllComponents((x)  => x.AlmostZero); } 
// AMBIGUOUS FUNCTIONS 2
        [MethodImpl(AggressiveInlining)]  public Vector8 Average(Vector8 y) => this.Lerp(y, ((Number)0.5));
[MethodImpl(AggressiveInlining)]  public Boolean Between(Vector8 a, Vector8 b) => this.AllZipComponents(a, b, (x1, a1, b1)  => x1.Between(a1, b1));
public Boolean Between01 { [MethodImpl(AggressiveInlining)] get  => this.AllComponents((x1)  => x1.Between01); } 
public Vector8 ClampZeroOne { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.ClampZeroOne); } 
public Vector8 Fract { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Fract); } 
[MethodImpl(AggressiveInlining)]  public Vector8 InversePow(Vector8 y) => this.ZipComponents(y, (x1, y1)  => x1.InversePow(y1));
[MethodImpl(AggressiveInlining)]  public Vector8 Lerp(Vector8 b, Number t){
            var _var211 = t;
            return this.ZipComponents(b, (a1, b1)  => a1.Lerp(b1, _var211));
        }

[MethodImpl(AggressiveInlining)]  public Vector8 MultiplyEpsilon(Vector8 y) => this.ZipComponents(y, (x1, y1)  => x1.MultiplyEpsilon(y1));
public Vector8 Pow2 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow2); } 
public Vector8 Pow3 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow3); } 
public Vector8 Pow4 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow4); } 
public Vector8 Pow5 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow5); } 
[MethodImpl(AggressiveInlining)]  public IArray<Vector8> Sample(Vector8 b, Integer n){
            var _var213 = b;
            {
                var _var212 = this;
                return n.LinearSpace.Map((i)  => _var212.Lerp(_var213, i));
            }
        }

public Vector8 Half { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)2)); } 
public Vector8 Quarter { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)4)); } 
public Vector8 Eight { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)8)); } 
public Vector8 Sixteenth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)16)); } 
public Vector8 Tenth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)10)); } 
public Vector8 Twice { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)2)); } 
public Vector8 Hundred { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)100)); } 
public Vector8 Thousand { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)1000)); } 
public Vector8 Million { [MethodImpl(AggressiveInlining)] get  => this.Thousand.Thousand; } 
public Vector8 Billion { [MethodImpl(AggressiveInlining)] get  => this.Thousand.Million; } 
public Vector8 Hundredth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)100)); } 
public Vector8 Thousandth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)1000)); } 
public Vector8 Millionth { [MethodImpl(AggressiveInlining)] get  => this.Thousandth.Thousandth; } 
public Vector8 Billionth { [MethodImpl(AggressiveInlining)] get  => this.Thousandth.Millionth; } 
[MethodImpl(AggressiveInlining)]  public Number At(Integer n) => this.Components.At(n);
public Number this[Integer n] { [MethodImpl(AggressiveInlining)]  get => At(n); }
        [MethodImpl(AggressiveInlining)]  public Vector8 MapComponents(System.Func<Number, Number> f) => Vector8.CreateFromComponents(this.Components.Map(f));
[MethodImpl(AggressiveInlining)]  public Vector8 ZipComponents(Vector8 b, System.Func<Number, Number, Number> f) => Vector8.CreateFromComponents(this.Components.Zip(b.Components, f));
[MethodImpl(AggressiveInlining)]  public Vector8 ZipComponents(Vector8 b, Vector8 c, System.Func<Number, Number, Number, Number> f) => Vector8.CreateFromComponents(this.Components.Zip(b.Components, c.Components, f));
[MethodImpl(AggressiveInlining)]  public Boolean AllZipComponents(Vector8 b, System.Func<Number, Number, Boolean> f) => this.Components.Zip(b.Components, f).All((x)  => x);
[MethodImpl(AggressiveInlining)]  public Boolean AllZipComponents(Vector8 b, Vector8 c, System.Func<Number, Number, Number, Boolean> f) => this.Components.Zip(b.Components, c.Components, f).All((x)  => x);
[MethodImpl(AggressiveInlining)]  public Boolean AnyZipComponents(Vector8 b, System.Func<Number, Number, Boolean> f) => this.Components.Zip(b.Components, f).Any((x)  => x);
[MethodImpl(AggressiveInlining)]  public Boolean AnyZipComponents(Vector8 b, Vector8 c, System.Func<Number, Number, Number, Boolean> f) => this.Components.Zip(b.Components, c.Components, f).Any((x)  => x);
[MethodImpl(AggressiveInlining)]  public Boolean AllComponents(System.Func<Number, Boolean> predicate) => this.Components.All(predicate);
[MethodImpl(AggressiveInlining)]  public Boolean AnyComponent(System.Func<Number, Boolean> predicate) => this.Components.Any(predicate);

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)]  public Vector8 Modulo(Vector8 b) => this % b;
        [MethodImpl(AggressiveInlining)]  public Vector8 Modulo(Number other) => this % other;
    }
}
