// Autogenerated file: DO NOT EDIT
// Created on 2025-01-17 3:12:39 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct ColorYCbCr: ICoordinate<ColorYCbCr>
    {
        // Fields
        [DataMember] public readonly Unit Y;
        [DataMember] public readonly Unit Cb;
        [DataMember] public readonly Unit Cr;

        // With functions 
        [MethodImpl(AggressiveInlining)] public ColorYCbCr WithY(Unit y) => new ColorYCbCr(y, Cb, Cr);
        [MethodImpl(AggressiveInlining)] public ColorYCbCr WithCb(Unit cb) => new ColorYCbCr(Y, cb, Cr);
        [MethodImpl(AggressiveInlining)] public ColorYCbCr WithCr(Unit cr) => new ColorYCbCr(Y, Cb, cr);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public ColorYCbCr(Unit y, Unit cb, Unit cr) { Y = y; Cb = cb; Cr = cr; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static ColorYCbCr Create(Unit y, Unit cb, Unit cr) => new ColorYCbCr(y, cb, cr);

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Unit, Unit, Unit)(ColorYCbCr self) => (self.Y, self.Cb, self.Cr);
        [MethodImpl(AggressiveInlining)] public static implicit operator ColorYCbCr((Unit, Unit, Unit) value) => new(value.Item1, value.Item2, value.Item3);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Unit y, out Unit cb, out Unit cr) { y = Y; cb = Cb; cr = Cr;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(ColorYCbCr other) => Y.Equals(other.Y) && Cb.Equals(other.Cb) && Cr.Equals(other.Cr);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is ColorYCbCr other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Y, Cb, Cr);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Y\" = {Y}, \"Cb\" = {Cb}, \"Cr\" = {Cr} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented concept functions and type functions
        [MethodImpl(AggressiveInlining)]  public IArray<ColorYCbCr> Repeat(Integer n){
            var _var37 = this;
            return n.MapRange((i) => _var37);
        }


        // Unimplemented concept functions
    }
}
