// Autogenerated file: DO NOT EDIT
// Created on 2025-01-29 8:54:01 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct ConicSection: IPolarCurve, IOpenShape
    {
        // Fields
        [DataMember] public readonly Number Eccentricity;
        [DataMember] public readonly Number SemiLatusRectum;

        // With functions 
        [MethodImpl(AggressiveInlining)] public ConicSection WithEccentricity(Number eccentricity) => new ConicSection(eccentricity, SemiLatusRectum);
        [MethodImpl(AggressiveInlining)] public ConicSection WithSemiLatusRectum(Number semiLatusRectum) => new ConicSection(Eccentricity, semiLatusRectum);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public ConicSection(Number eccentricity, Number semiLatusRectum) { Eccentricity = eccentricity; SemiLatusRectum = semiLatusRectum; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static ConicSection Create(Number eccentricity, Number semiLatusRectum) => new ConicSection(eccentricity, semiLatusRectum);

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number)(ConicSection self) => (self.Eccentricity, self.SemiLatusRectum);
        [MethodImpl(AggressiveInlining)] public static implicit operator ConicSection((Number, Number) value) => new(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number eccentricity, out Number semiLatusRectum) { eccentricity = Eccentricity; semiLatusRectum = SemiLatusRectum;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(ConicSection other) => Eccentricity.Equals(other.Eccentricity) && SemiLatusRectum.Equals(other.SemiLatusRectum);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(ConicSection other) => !Eccentricity.Equals(other.Eccentricity) && SemiLatusRectum.Equals(other.SemiLatusRectum);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is ConicSection other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Eccentricity, SemiLatusRectum);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Eccentricity\" = {Eccentricity}, \"SemiLatusRectum\" = {SemiLatusRectum} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented concept functions and type functions
        [MethodImpl(AggressiveInlining)]  public Number GetRadius(Angle t) => t.ConicSection(this.SemiLatusRectum, this.Eccentricity);
        [MethodImpl(AggressiveInlining)]  public PolarCoordinate EvalPolar(Angle t) => (this.GetRadius(t), t);
        [MethodImpl(AggressiveInlining)]  public Vector2 Eval(Angle t) => this.EvalPolar(t);
        [MethodImpl(AggressiveInlining)]  public Vector2 Eval(Number t) => this.Eval(t.Turns);
        [MethodImpl(AggressiveInlining)]  public IArray<Vector2> Sample(Integer numPoints){
            var _var57 = this;
            return numPoints.LinearSpace.Map((x) => _var57.Eval(x));
        }

        [MethodImpl(AggressiveInlining)]  public PolyLine2D ToPolyLine2D(Integer numPoints) => (this.Sample(numPoints), this.Closed);
        public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => ((Boolean)false); } 

        // Unimplemented concept functions
        [MethodImpl(AggressiveInlining)]  public Number Distance(Vector2 p) => throw new NotImplementedException();
    }
}
