// Autogenerated file: DO NOT EDIT
// Created on 2025-03-09 11:25:56 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Epicycloid: IAngularCurve2D, IOpenShape
    {
        // Fields
        [DataMember] public readonly Number Radius1;
        [DataMember] public readonly Number Radius2;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Epicycloid WithRadius1(Number radius1) => new Epicycloid(radius1, Radius2);
        [MethodImpl(AggressiveInlining)] public Epicycloid WithRadius2(Number radius2) => new Epicycloid(Radius1, radius2);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Epicycloid(Number radius1, Number radius2) { Radius1 = radius1; Radius2 = radius2; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Epicycloid Create(Number radius1, Number radius2) => new Epicycloid(radius1, radius2);

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number)(Epicycloid self) => (self.Radius1, self.Radius2);
        [MethodImpl(AggressiveInlining)] public static implicit operator Epicycloid((Number, Number) value) => new(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number radius1, out Number radius2) { radius1 = Radius1; radius2 = Radius2;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Epicycloid other) => Radius1.Equals(other.Radius1) && Radius2.Equals(other.Radius2);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Epicycloid other) => !Radius1.Equals(other.Radius1) && Radius2.Equals(other.Radius2);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Epicycloid other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Radius1, Radius2);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Radius1\" = {Radius1}, \"Radius2\" = {Radius2} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented concept functions and type functions
        [MethodImpl(AggressiveInlining)]  public Vector2 Eval(Angle t) => t.Epicycloid(this.Radius1, this.Radius2);
        [MethodImpl(AggressiveInlining)]  public Vector2 Eval(Number t) => this.Eval(t.Turns);
        [MethodImpl(AggressiveInlining)]  public IArray<Vector2> Sample(Integer numPoints){
            var _var144 = this;
            return numPoints.LinearSpace.Map((x) => _var144.Eval(x));
        }

        [MethodImpl(AggressiveInlining)]  public PolyLine2D ToPolyLine2D(Integer numPoints) => (this.Sample(numPoints), this.Closed);
        [MethodImpl(AggressiveInlining)]  public Procedural<Number, TR> Combine<TR>(Epicycloid b, System.Func<TR, TR, TR> f){
            var _var147 = b;
            {
                var _var146 = this;
                {
                    var _var145 = f;
                    return (x) => _var145.Invoke(_var146.Eval(x), _var147.Eval(x));
                }
            }
        }

        [MethodImpl(AggressiveInlining)]  public Procedural<TR, Vector2> MapDomain<T0, TR>(System.Func<T0, TR> f){
            var _var149 = f;
            {
                var _var148 = this;
                return (x) => _var148.Eval(_var149.Invoke(x));
            }
        }

        public System.Func<Number, Vector2> Function { [MethodImpl(AggressiveInlining)] get {
            var _var150 = this;
            return (x) => _var150.Eval(x);
        }
         } 
        [MethodImpl(AggressiveInlining)]  public Procedural<Number, Vector2> Compose(Epicycloid b){
            var _var152 = this;
            {
                var _var151 = b;
                return (x) => _var151.Eval(_var152.Eval(x));
            }
        }

        [MethodImpl(AggressiveInlining)]  public Procedural<Vector2, TR> Combine<TR>(Epicycloid b, System.Func<TR, TR, TR> f){
            var _var155 = b;
            {
                var _var154 = this;
                {
                    var _var153 = f;
                    return (x) => _var153.Invoke(_var154.Eval(x), _var155.Eval(x));
                }
            }
        }

        [MethodImpl(AggressiveInlining)]  public Procedural<TR, Number> MapDomain<T0, TR>(System.Func<T0, TR> f){
            var _var157 = f;
            {
                var _var156 = this;
                return (x) => _var156.Eval(_var157.Invoke(x));
            }
        }

        public System.Func<Vector2, Number> Function { [MethodImpl(AggressiveInlining)] get {
            var _var158 = this;
            return (x) => _var158.Eval(x);
        }
         } 
        [MethodImpl(AggressiveInlining)]  public Procedural<Vector2, Number> Compose(Epicycloid b){
            var _var160 = this;
            {
                var _var159 = b;
                return (x) => _var159.Eval(_var160.Eval(x));
            }
        }

        [MethodImpl(AggressiveInlining)]  public Procedural<Vector2, $TOut> Union(Epicycloid b) => this.Combine(b, (a, b) => a.Max(b));
        [MethodImpl(AggressiveInlining)]  public Procedural<Vector2, $TOut> Intersection(Epicycloid b) => this.Combine(b, (a, b) => a.Min(b));
        [MethodImpl(AggressiveInlining)]  public Procedural<Vector2, $TOut> Difference(Epicycloid b) => this.Combine(b, (a, b) => a.Max(b.Negative));
        public Procedural<Vector2, Number> Inverse { [MethodImpl(AggressiveInlining)] get  => this.Map((x) => x.Negative); } 
        public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => ((Boolean)false); } 

        // Unimplemented concept functions
        [MethodImpl(AggressiveInlining)]  public Number Distance(Vector2 p) => throw new NotImplementedException();
        [MethodImpl(AggressiveInlining)]  public Number Eval(Vector2 t) => throw new NotImplementedException();
    }
}
