// Autogenerated file: DO NOT EDIT
// Created on 2025-01-17 3:12:39 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    public interface IAny
    {
    }
    public interface IValue<Self>: IAny, IEquatable<Self>
    {
    }
    public interface INumerical<Self>: IValue<Self>, IScalarArithmetic<Self>, IAdditive<Self>
    {
        IArray<Number> Components { get; }
        Self FromComponents(IArray<Number> xs);
    }
    public interface INumberLike<Self>: INumerical<Self>, IOrderable<Self>
    {
        Number ToNumber { get; }
        Self FromNumber(Number n);
    }
    public interface IReal<Self>: INumberLike<Self>, IAlgebraic<Self>, IArithmetic<Self>
    {
    }
    public interface IWholeNumber<Self>: IValue<Self>, IOrderable<Self>, IArithmetic<Self>
    {
    }
    public interface IMeasure<Self>: INumberLike<Self>, IAdditive<Self>, IInterpolatable<Self>
    {
    }
    public interface IVector<Self>: INumerical<Self>, IArithmetic<Self>, IArray<Number>, IInterpolatable<Self>, IAlgebraic<Self>
    {
    }
    public interface ICoordinate<Self>: IValue<Self>
    {
    }
    public interface IOrderable<Self>: IEquatable<Self>
    {
        Boolean LessThanOrEquals(Self y);
    }
    public interface IEquatable<Self>: IAny
    {
        Boolean Equals(Self b);
    }
    public interface IAdditive<Self>: IAny
    {
        Self Add(Self b);
        Self Subtract(Self b);
        Self Negative { get; }
    }
    public interface IScalarArithmetic<Self>: IAny
    {
        Self Modulo(Number other);
        Self Divide(Number other);
        Self Multiply(Number other);
    }
    public interface IMultiplicative<Self>: IAny
    {
        Self Multiply(Self b);
    }
    public interface IInvertible<Self>: IAny
    {
        Self Inverse { get; }
    }
    public interface IMultiplicativeWithInverse<Self>: IMultiplicative<Self>, IInvertible<Self>
    {
    }
    public interface IAlgebraic<Self>: IInterpolatable<Self>, IMultiplicative<Self>
    {
    }
    public interface IInterpolatable<Self>: IAdditive<Self>, IScalarArithmetic<Self>
    {
    }
    public interface IDivisible<Self>: IAny
    {
        Self Divide(Self b);
    }
    public interface IModulo<Self>: IAny
    {
        Self Modulo(Self b);
    }
    public interface IArithmetic<Self>: IAdditive<Self>, IMultiplicative<Self>, IDivisible<Self>, IModulo<Self>
    {
    }
    public interface IBoolean<Self>: IAny
    {
        Self And(Self b);
        Self Or(Self b);
        Self Not { get; }
    }
    public interface IInterval<Self, T>: IEquatable<Self>, IValue<Self>, IArray<T>
    {
        T Start { get; }
        T End { get; }
    }
    public interface IBounds<Self, T>: IEquatable<Self>, IValue<Self>
    {
        T Min { get; }
        T Max { get; }
    }
    public interface IRealFunction
    {
        Number Eval(Number x);
    }
    public interface IAngularCurve2D: ICurve2D
    {
        Vector2 GetPoint(Angle t);
    }
    public interface IPolarCurve: IAngularCurve2D
    {
        Number GetRadius(Angle t);
    }
    public interface IAngularCurve3D: ICurve3D
    {
        Vector3 GetPoint(Angle t);
    }
    public interface IBounded2D
    {
        Bounds2D Bounds { get; }
    }
    public interface IBounded3D
    {
        Bounds3D Bounds { get; }
    }
    public interface IDeformable2D<Self>
    {
        Self Deform(System.Func<Vector2, Vector2> f);
    }
    public interface IOpenClosedShape
    {
        Boolean Closed { get; }
    }
    public interface IDeformable3D<Self>
    {
        Self Deform(System.Func<Vector3, Vector3> f);
    }
    public interface IGeometry
    {
    }
    public interface IGeometry2D: IGeometry
    {
    }
    public interface IGeometry3D: IGeometry
    {
    }
    public interface IShape2D: IGeometry2D
    {
    }
    public interface IShape3D: IGeometry3D
    {
    }
    public interface IOpenShape: IOpenClosedShape
    {
    }
    public interface IClosedShape: IOpenClosedShape
    {
    }
    public interface IOpenShape2D: IGeometry2D, IOpenShape
    {
    }
    public interface IClosedShape2D: IGeometry2D, IClosedShape
    {
    }
    public interface IOpenShape3D: IGeometry3D, IOpenShape
    {
    }
    public interface IClosedShape3D: IGeometry3D, IClosedShape
    {
    }
    public interface IProcedural<TDomain, TRange>
    {
        TRange Eval(TDomain t);
    }
    public interface ICurve<TRange>: IProcedural<Number, TRange>, IOpenClosedShape
    {
    }
    public interface IDistanceField2D
    {
        Number Distance(Vector2 p);
    }
    public interface IDistanceField3D
    {
        Number Distance(Vector3 p);
    }
    public interface ICurve1D: ICurve<Number>
    {
    }
    public interface ICurve2D: IGeometry2D, ICurve<Vector2>, IDistanceField2D
    {
    }
    public interface IClosedCurve2D: ICurve2D, IClosedShape2D
    {
    }
    public interface IOpenCurve2D: ICurve2D, IOpenShape2D
    {
    }
    public interface ICurve3D: IGeometry3D, ICurve<Vector3>, IDistanceField3D
    {
    }
    public interface IClosedCurve3D: ICurve3D, IClosedShape3D
    {
    }
    public interface IOpenCurve3D: ICurve3D, IOpenShape3D
    {
    }
    public interface ISurface: IGeometry3D, IDistanceField3D
    {
    }
    public interface IProceduralSurface: IProcedural<Vector2, Vector3>, ISurface
    {
        Boolean ClosedX { get; }
        Boolean ClosedY { get; }
    }
    public interface IExplicitSurface: IProcedural<Vector2, Number>, ISurface
    {
    }
    public interface IImplicitProcedural<TDomain>: IProcedural<TDomain, Boolean>
    {
    }
    public interface IImplicitSurface: ISurface, IImplicitProcedural<Vector3>
    {
    }
    public interface IImplicitCurve2D: IGeometry2D, IImplicitProcedural<Vector2>
    {
    }
    public interface IImplicitVolume: IGeometry3D, IImplicitProcedural<Vector3>
    {
    }
    public interface IPolyLine2D: IPointGeometry2D, IOpenClosedShape, ICurve2D
    {
    }
    public interface IPolyLine3D<Self>: IPointGeometry3D<Self>, IOpenClosedShape, ICurve3D
    {
    }
    public interface IClosedPolyLine2D: IPolyLine2D, IClosedShape2D
    {
    }
    public interface IClosedPolyLine3D<Self>: IPolyLine3D<Self>, IClosedShape3D
    {
    }
    public interface IPolygon2D: IClosedPolyLine2D, IArray<Vector2>
    {
    }
    public interface IPolygon3D<Self>: IClosedPolyLine3D<Self>, IArray<Vector3>
    {
    }
    public interface ISolid: IProceduralSurface
    {
    }
    public interface IPrimitiveGeometry
    {
        Integer PrimitiveSize { get; }
        Integer NumPrimitives { get; }
    }
    public interface IPointPrimitives: IPrimitiveGeometry
    {
    }
    public interface ILinePrimitives: IPrimitiveGeometry
    {
    }
    public interface ITrianglePrimitives: IPrimitiveGeometry
    {
    }
    public interface IQuadPrimitives: IPrimitiveGeometry
    {
    }
    public interface IPointGeometry2D: IGeometry2D
    {
        IArray<Vector2> Points { get; }
    }
    public interface IPointGeometry3D<Self>: IGeometry3D, IDeformable3D<Self>
    {
        IArray<Vector3> Points { get; }
    }
    public interface IPrimitiveGeometry2D: IPointGeometry2D, IPrimitiveGeometry
    {
    }
    public interface IPrimitiveGeometry3D<Self>: IPointGeometry3D<Self>, IPrimitiveGeometry
    {
    }
    public interface ILineGeometry2D: IPrimitiveGeometry2D, ILinePrimitives
    {
        IArray<Line2D> Lines { get; }
    }
    public interface ILineGeometry3D<Self>: IPrimitiveGeometry3D<Self>, ILinePrimitives
    {
        IArray<Line3D> Lines { get; }
    }
    public interface ITriangleGeometry2D: IPrimitiveGeometry2D, ITrianglePrimitives
    {
        IArray<Triangle2D> Triangles { get; }
    }
    public interface ITriangleGeometry3D<Self>: IPrimitiveGeometry3D<Self>, ITrianglePrimitives
    {
        IArray<Triangle3D> Triangles { get; }
    }
    public interface IQuadGeometry2D: IPrimitiveGeometry2D, IQuadPrimitives
    {
        IArray<Quad2D> Quads { get; }
    }
    public interface IQuadGeometry3D<Self>: IPrimitiveGeometry3D<Self>, IQuadPrimitives
    {
        IArray<Quad3D> Quads { get; }
    }
    public interface IIndexedGeometry: IPrimitiveGeometry
    {
        IArray<Integer> Indices { get; }
    }
    public interface IIndexedGeometry2D: IIndexedGeometry, IPrimitiveGeometry2D
    {
    }
    public interface IIndexedGeometry3D<Self>: IIndexedGeometry, IPrimitiveGeometry3D<Self>
    {
    }
    public interface ILineMesh2D: IIndexedGeometry2D, ILineGeometry2D
    {
    }
    public interface ILineMesh3D<Self>: IIndexedGeometry3D<Self>, ILineGeometry3D<Self>
    {
    }
    public interface ITriangleMesh2D: IIndexedGeometry2D, ITriangleGeometry2D
    {
    }
    public interface ITriangleMesh3D<Self>: IIndexedGeometry3D<Self>, ITriangleGeometry3D<Self>
    {
    }
    public interface IQuadMesh2D: IIndexedGeometry2D, IQuadGeometry2D
    {
    }
    public interface IQuadMesh3D<Self>: IIndexedGeometry3D<Self>, IQuadGeometry3D<Self>
    {
    }
    public interface IPointArray2D: IPointGeometry2D
    {
    }
    public interface IPointArray3D<Self>: IPointGeometry3D<Self>
    {
    }
    public interface ILineArray2D: ILineMesh2D
    {
    }
    public interface ILineArray3D<Self>: ILineMesh3D<Self>
    {
    }
    public interface ITriangleArray2D: ITriangleMesh2D
    {
    }
    public interface ITriangleArray3D<Self>: ITriangleMesh3D<Self>
    {
    }
    public interface IQuadArray2D: IQuadMesh2D
    {
    }
    public interface IQuadArray3D<Self>: IQuadMesh3D<Self>
    {
    }
    public interface IQuadGrid3D<Self>: IQuadMesh3D<Self>
    {
        IArray2D<Vector3> PointGrid { get; }
        Boolean ClosedX { get; }
        Boolean ClosedY { get; }
    }
    public interface ITransform3D
    {
        Vector3 Transform(Vector3 v);
        Vector3 TransformNormal(Vector3 v);
        Matrix4x4 Matrix { get; }
    }
    public interface IRotationalTransform3D: ITransform3D
    {
        Quaternion Quaternion { get; }
    }
}
