// Autogenerated file: DO NOT EDIT
// Created on 2025-01-29 8:54:01 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct PointArray2D: IPointArray2D
    {
        // Fields
        [DataMember] public readonly IArray<Vector2> Points;

        // With functions 
        [MethodImpl(AggressiveInlining)] public PointArray2D WithPoints(IArray<Vector2> points) => new PointArray2D(points);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public PointArray2D(IArray<Vector2> points) { Points = points; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static PointArray2D Create(IArray<Vector2> points) => new PointArray2D(points);

        // Implicit converters to/from single field

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(PointArray2D other) => Points.Equals(other.Points);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(PointArray2D other) => !Points.Equals(other.Points);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is PointArray2D other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Points);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Points\" = {Points} }}";

        // Explicit implementation of interfaces by forwarding properties to fields
        IArray<Vector2> IPointGeometry2D.Points { [MethodImpl(AggressiveInlining)] get => Points; }

        // Implemented concept functions and type functions

        // Unimplemented concept functions
    }
}
