// Autogenerated file: DO NOT EDIT
// Created on 2025-03-09 11:25:56 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Quad2D: IPolygon2D
    {
        // Fields
        [DataMember] public readonly Vector2 A;
        [DataMember] public readonly Vector2 B;
        [DataMember] public readonly Vector2 C;
        [DataMember] public readonly Vector2 D;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Quad2D WithA(Vector2 a) => new Quad2D(a, B, C, D);
        [MethodImpl(AggressiveInlining)] public Quad2D WithB(Vector2 b) => new Quad2D(A, b, C, D);
        [MethodImpl(AggressiveInlining)] public Quad2D WithC(Vector2 c) => new Quad2D(A, B, c, D);
        [MethodImpl(AggressiveInlining)] public Quad2D WithD(Vector2 d) => new Quad2D(A, B, C, d);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Quad2D(Vector2 a, Vector2 b, Vector2 c, Vector2 d) { A = a; B = b; C = c; D = d; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Quad2D Create(Vector2 a, Vector2 b, Vector2 c, Vector2 d) => new Quad2D(a, b, c, d);

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Vector2, Vector2, Vector2, Vector2)(Quad2D self) => (self.A, self.B, self.C, self.D);
        [MethodImpl(AggressiveInlining)] public static implicit operator Quad2D((Vector2, Vector2, Vector2, Vector2) value) => new(value.Item1, value.Item2, value.Item3, value.Item4);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Vector2 a, out Vector2 b, out Vector2 c, out Vector2 d) { a = A; b = B; c = C; d = D;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Quad2D other) => A.Equals(other.A) && B.Equals(other.B) && C.Equals(other.C) && D.Equals(other.D);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Quad2D other) => !A.Equals(other.A) && B.Equals(other.B) && C.Equals(other.C) && D.Equals(other.D);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Quad2D other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(A, B, C, D);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"A\" = {A}, \"B\" = {B}, \"C\" = {C}, \"D\" = {D} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented concept functions and type functions
        public Quad2D Flip { [MethodImpl(AggressiveInlining)] get  => (this.D, this.C, this.B, this.A); } 
        public Vector2 Center { [MethodImpl(AggressiveInlining)] get  => this.A.Add(this.B.Add(this.C.Add(this.D))).Divide(((Number)4)); } 
        public Line2D LineA { [MethodImpl(AggressiveInlining)] get  => (this.A, this.B); } 
        public Line2D LineB { [MethodImpl(AggressiveInlining)] get  => (this.B, this.C); } 
        public Line2D LineC { [MethodImpl(AggressiveInlining)] get  => (this.C, this.D); } 
        public Line2D LineD { [MethodImpl(AggressiveInlining)] get  => (this.D, this.A); } 
        public Triangle2D TriangleA { [MethodImpl(AggressiveInlining)] get  => (this.A, this.B, this.C); } 
        public Triangle2D TriangleB { [MethodImpl(AggressiveInlining)] get  => (this.C, this.D, this.A); } 
        public Quad3D To3D { [MethodImpl(AggressiveInlining)] get  => (this.A.To3D, this.B.To3D, this.C.To3D, this.D.To3D); } 
        public Quad3D Quad3D { [MethodImpl(AggressiveInlining)] get  => this.To3D; } 
        [MethodImpl(AggressiveInlining)]  public static implicit operator Quad3D(Quad2D x) => x.Quad3D;
        public static Quad2D Unit { [MethodImpl(AggressiveInlining)] get  => ((((Number)0), ((Number)0)), (((Number)1), ((Number)0)), (((Number)1), ((Number)1)), (((Number)0), ((Number)1))); } 
        public LineArray2D LineArray2D { [MethodImpl(AggressiveInlining)] get  => new LineArray2D(this.Lines); } 
        [MethodImpl(AggressiveInlining)]  public static implicit operator LineArray2D(Quad2D q) => q.LineArray2D;
        public TriangleArray2D TriangleArray2D { [MethodImpl(AggressiveInlining)] get  => new TriangleArray2D(this.Triangles); } 
        [MethodImpl(AggressiveInlining)]  public static implicit operator TriangleArray2D(Quad2D q) => q.TriangleArray2D;
        public IArray<Vector2> Points { [MethodImpl(AggressiveInlining)] get  => Intrinsics.MakeArray<Vector2>(this.A, this.B, this.C, this.D); } 
        public IArray<Line2D> Lines { [MethodImpl(AggressiveInlining)] get  => Intrinsics.MakeArray<Line2D>(new Line2D(this.A, this.B), new Line2D(this.B, this.C), new Line2D(this.C, this.D), new Line2D(this.D, this.A)); } 
        public IArray<Triangle2D> Triangles { [MethodImpl(AggressiveInlining)] get  => Intrinsics.MakeArray<Triangle2D>(new Triangle2D(this.A, this.B, this.C), new Triangle2D(this.C, this.D, this.A)); } 
        [MethodImpl(AggressiveInlining)]  public IArray<Vector2> Sample(Integer numPoints){
            var _var552 = this;
            return numPoints.LinearSpace.Map((x) => _var552.Eval(x));
        }

        [MethodImpl(AggressiveInlining)]  public PolyLine2D ToPolyLine2D(Integer numPoints) => (this.Sample(numPoints), this.Closed);
        [MethodImpl(AggressiveInlining)]  public Procedural<Number, TR> Combine<TR>(Quad2D b, System.Func<TR, TR, TR> f){
            var _var555 = b;
            {
                var _var554 = this;
                {
                    var _var553 = f;
                    return (x) => _var553.Invoke(_var554.Eval(x), _var555.Eval(x));
                }
            }
        }

        [MethodImpl(AggressiveInlining)]  public Procedural<TR, Vector2> MapDomain<T0, TR>(System.Func<T0, TR> f){
            var _var557 = f;
            {
                var _var556 = this;
                return (x) => _var556.Eval(_var557.Invoke(x));
            }
        }

        public System.Func<Number, Vector2> Function { [MethodImpl(AggressiveInlining)] get {
            var _var558 = this;
            return (x) => _var558.Eval(x);
        }
         } 
        [MethodImpl(AggressiveInlining)]  public Procedural<Number, Vector2> Compose(Quad2D b){
            var _var560 = this;
            {
                var _var559 = b;
                return (x) => _var559.Eval(_var560.Eval(x));
            }
        }

        [MethodImpl(AggressiveInlining)]  public Procedural<Vector2, TR> Combine<TR>(Quad2D b, System.Func<TR, TR, TR> f){
            var _var563 = b;
            {
                var _var562 = this;
                {
                    var _var561 = f;
                    return (x) => _var561.Invoke(_var562.Eval(x), _var563.Eval(x));
                }
            }
        }

        [MethodImpl(AggressiveInlining)]  public Procedural<TR, Number> MapDomain<T0, TR>(System.Func<T0, TR> f){
            var _var565 = f;
            {
                var _var564 = this;
                return (x) => _var564.Eval(_var565.Invoke(x));
            }
        }

        public System.Func<Vector2, Number> Function { [MethodImpl(AggressiveInlining)] get {
            var _var566 = this;
            return (x) => _var566.Eval(x);
        }
         } 
        [MethodImpl(AggressiveInlining)]  public Procedural<Vector2, Number> Compose(Quad2D b){
            var _var568 = this;
            {
                var _var567 = b;
                return (x) => _var567.Eval(_var568.Eval(x));
            }
        }

        [MethodImpl(AggressiveInlining)]  public Procedural<Vector2, $TOut> Union(Quad2D b) => this.Combine(b, (a, b) => a.Max(b));
        [MethodImpl(AggressiveInlining)]  public Procedural<Vector2, $TOut> Intersection(Quad2D b) => this.Combine(b, (a, b) => a.Min(b));
        [MethodImpl(AggressiveInlining)]  public Procedural<Vector2, $TOut> Difference(Quad2D b) => this.Combine(b, (a, b) => a.Max(b.Negative));
        public Procedural<Vector2, Number> Inverse { [MethodImpl(AggressiveInlining)] get  => this.Map((x) => x.Negative); } 
        public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => ((Boolean)true); } 

        // Unimplemented concept functions
        [MethodImpl(AggressiveInlining)]  public Number Distance(Vector2 p) => throw new NotImplementedException();
        [MethodImpl(AggressiveInlining)]  public Number Eval(Vector2 t) => throw new NotImplementedException();
        [MethodImpl(AggressiveInlining)]  public Vector2 Eval(Number t) => throw new NotImplementedException();
        public IArray<Vector2> Corners => throw new NotImplementedException();
        public Integer PrimitiveSize => throw new NotImplementedException();
        public Integer NumPrimitives => throw new NotImplementedException();
    }
}
