// Autogenerated file: DO NOT EDIT
// Created on 2025-01-20 10:41:00 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;

namespace Plato
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct TriangleMesh3D: ITriangleMesh3D<TriangleMesh3D>
    {
        // Fields
        [DataMember] public readonly IArray<Vector3> Points;
        [DataMember] public readonly IArray<Integer> Indices;

        // With functions 
        [MethodImpl(AggressiveInlining)] public TriangleMesh3D WithPoints(IArray<Vector3> points) => new TriangleMesh3D(points, Indices);
        [MethodImpl(AggressiveInlining)] public TriangleMesh3D WithIndices(IArray<Integer> indices) => new TriangleMesh3D(Points, indices);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public TriangleMesh3D(IArray<Vector3> points, IArray<Integer> indices) { Points = points; Indices = indices; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static TriangleMesh3D Create(IArray<Vector3> points, IArray<Integer> indices) => new TriangleMesh3D(points, indices);

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (IArray<Vector3>, IArray<Integer>)(TriangleMesh3D self) => (self.Points, self.Indices);
        [MethodImpl(AggressiveInlining)] public static implicit operator TriangleMesh3D((IArray<Vector3>, IArray<Integer>) value) => new(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out IArray<Vector3> points, out IArray<Integer> indices) { points = Points; indices = Indices;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(TriangleMesh3D other) => Points.Equals(other.Points) && Indices.Equals(other.Indices);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(TriangleMesh3D other) => !Points.Equals(other.Points) && Indices.Equals(other.Indices);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is TriangleMesh3D other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Points, Indices);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Points\" = {Points}, \"Indices\" = {Indices} }}";

        // Explicit implementation of interfaces by forwarding properties to fields
        IArray<Integer> IIndexedGeometry.Indices { [MethodImpl(AggressiveInlining)] get => Indices; }
        IArray<Vector3> IPointGeometry3D<TriangleMesh3D>.Points { [MethodImpl(AggressiveInlining)] get => Points; }

        // Implemented concept functions and type functions
        [MethodImpl(AggressiveInlining)]  public TriangleMesh3D Deform(System.Func<Vector3, Vector3> f) => (this.Points.Map(f), this.Indices);
        public LineMesh3D LineMesh3D { [MethodImpl(AggressiveInlining)] get  => (this.Points, this.AllFaceIndices.FlatMap((a) => Intrinsics.MakeArray(a.At(((Integer)0)), a.At(((Integer)1)), a.At(((Integer)2)), a.At(((Integer)0))))); } 
        [MethodImpl(AggressiveInlining)]  public static implicit operator LineMesh3D(TriangleMesh3D g) => g.LineMesh3D;
        public IArray<Triangle3D> Faces { [MethodImpl(AggressiveInlining)] get  => this.Triangles; } 
        public IArray<Triangle3D> Triangles { [MethodImpl(AggressiveInlining)] get  => this.AllFaceVertices.Map((xs) => new Triangle3D(xs.At(((Integer)0)), xs.At(((Integer)1)), xs.At(((Integer)2)))); } 
        [MethodImpl(AggressiveInlining)]  public IArray<Vector3> FaceVertices(Integer f){
            var _var150 = this;
            return this.FaceIndices(f).Map((i) => _var150.Vertex(i));
        }

        [MethodImpl(AggressiveInlining)]  public Vector3 Vertex(Integer n) => this.Points.At(this.Indices.At(n));
        [MethodImpl(AggressiveInlining)]  public IArray<Vector3> Vertices(IArray<Integer> xs){
            var _var151 = this;
            return xs.Map((i) => _var151.Vertex(i));
        }

        public IArray<IArray<Vector3>> AllFaceVertices { [MethodImpl(AggressiveInlining)] get {
            var _var152 = this;
            return this.Indices.Slices(this.PrimitiveSize).Map((xs) => _var152.Vertices(xs));
        }
         } 
        public IArray<Vector3> AllVertices { [MethodImpl(AggressiveInlining)] get  => this.Vertices(this.Indices); } 
        public Integer NumPrimitives { [MethodImpl(AggressiveInlining)] get  => this.Indices.Count.Divide(this.PrimitiveSize); } 
        public Integer NumFaces { [MethodImpl(AggressiveInlining)] get  => this.NumPrimitives; } 
        [MethodImpl(AggressiveInlining)]  public IArray<Integer> FaceIndices(Integer f) => this.Indices.NthSlice(f, this.PrimitiveSize);
        public IArray<IArray<Integer>> AllFaceIndices { [MethodImpl(AggressiveInlining)] get  => this.Indices.Slices(this.PrimitiveSize); } 
        [MethodImpl(AggressiveInlining)]  public TriangleMesh3D Deform(ITransform3D t){
            var _var153 = t;
            return this.Deform((v) => _var153.Transform(v));
        }

        [MethodImpl(AggressiveInlining)]  public TriangleMesh3D Translate(Vector3 v){
            var _var154 = v;
            return this.Deform((p) => p.Add(_var154));
        }

        [MethodImpl(AggressiveInlining)]  public TriangleMesh3D Rotate(Quaternion q) => this.Deform(q);
        [MethodImpl(AggressiveInlining)]  public TriangleMesh3D Scale(Vector3 v){
            var _var155 = v;
            return this.Deform((p) => p.Multiply(_var155));
        }

        [MethodImpl(AggressiveInlining)]  public TriangleMesh3D Scale(Number s){
            var _var156 = s;
            return this.Deform((p) => p.Multiply(_var156));
        }

        [MethodImpl(AggressiveInlining)]  public TriangleMesh3D RotateX(Angle a) => this.Rotate(a.RotateX);
        [MethodImpl(AggressiveInlining)]  public TriangleMesh3D RotateY(Angle a) => this.Rotate(a.RotateY);
        [MethodImpl(AggressiveInlining)]  public TriangleMesh3D RotateZ(Angle a) => this.Rotate(a.RotateZ);
        [MethodImpl(AggressiveInlining)]  public TriangleMesh3D TranslateX(Number s){
            var _var157 = s;
            return this.Deform((p) => p.Add((_var157, ((Integer)0), ((Integer)0))));
        }

        [MethodImpl(AggressiveInlining)]  public TriangleMesh3D TranslateY(Number s){
            var _var158 = s;
            return this.Deform((p) => p.Add((((Integer)0), _var158, ((Integer)0))));
        }

        [MethodImpl(AggressiveInlining)]  public TriangleMesh3D TranslateZ(Number s){
            var _var159 = s;
            return this.Deform((p) => p.Add((((Integer)0), ((Integer)0), _var159)));
        }

        [MethodImpl(AggressiveInlining)]  public TriangleMesh3D ScaleX(Number s){
            var _var160 = s;
            return this.Deform((p) => p.Multiply((_var160, ((Integer)1), ((Integer)1))));
        }

        [MethodImpl(AggressiveInlining)]  public TriangleMesh3D ScaleY(Number s){
            var _var161 = s;
            return this.Deform((p) => p.Multiply((((Integer)1), _var161, ((Integer)1))));
        }

        [MethodImpl(AggressiveInlining)]  public TriangleMesh3D ScaleZ(Number s){
            var _var162 = s;
            return this.Deform((p) => p.Multiply((((Integer)1), ((Integer)1), _var162)));
        }

        public Integer PrimitiveSize { [MethodImpl(AggressiveInlining)] get  => ((Integer)3); } 

        // Unimplemented concept functions
    }
}
